### ISSUE TITLE
(bug) Posting Journal Large Aggregation Labels

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1110]
This Posting Journal UI does not provide an easy way to view aggregations at the bottom of the grid.  The text label obscures the amount aggregated, resulting in a poor user experience.  See below:

![largeaggregationlabels](https://cloud.githubusercontent.com/assets/896472/22176396/aab21fe8-e009-11e6-87a0-13b865feb36c.png)

**Comment by patsonjunior** [comment]
We suggest that the "Reference" column of the Posting journal accurately refers to the information that is found in the "Enregistrement" column of the same journal because it refers to parts that support the entries or transactions made in accounting. This makes it possible to remain very logical with the presentation of the register of invoicing or payment, ... 

Thus, we really do not know how to appreciate the importance of the column "Registration" unless it has a valid reason that would push us to leave it as such.

![journal de saisie](https://cloud.githubusercontent.com/assets/25841277/23356421/025c0104-fcda-11e6-8fe4-1f9bd9c76509.png)

![registre des factures](https://cloud.githubusercontent.com/assets/25841277/23356583/b24db92c-fcda-11e6-93e9-aca9d1fefaf7.png)

**Comment by jniles** [comment]
These have been addressed.
