### ISSUE TITLE
(bug/feature request) Cannot set the "is_convention" flag on the debtor groups page

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#1111]
On the debtor groups back-end table, there is an `is_convention` flag that determines the debtor group is a convention or not.  Unfortunately, there is no option to set this flag on the client.  It's likely because there was no proposed behavior

**Proposed Behavior**
I propose that we define the `is_convention` flag as a debtor group that is allowed to receive treatment without requiring the debtors pay cash.  In fact, the application should send a warning if the debtors attempt to pay cash.  Therefore, in English, I would label these as "Non Cash Clients".

The following properties should be applied:
 1. All invoices to members of the group will be marked as "covered by {{ debtor group }}" clearly underneath the total.  This will inform the pharmacy, laboratory, service, etc, that they don't need to provide proof of payment to receive care.
 2. All groups marked as `is_convention` have the option of receiving their invoice automatically by email at the end of the month.
 3. The Cash Payments window will make an `alert` if an `is_convention` patient tries to pay at the cash window.
 4. The voucher tool for convention payments will filter on `is_convention` to allow for balancing of an entire convention's bills at once.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by lomamech** [comment]
My question is as follows: the hospitals staff, for example, belong to a group of debtors that is not a convention but are allowed to receive treatment without requiring the debtors pay cash.

My second question is what is the difference between apply_billing_services and is_convention because in the label of apply_billing_services it is "With this configuration option checked all members of this debtor group will be exempt from paying automatically applied billing services"

**Comment by jniles** [comment]
@lomamech, thanks for your feedback.  I agree with both your points.

How about a flag that just says `allow_cash_payments` or something similar?  That way, we can block people from paying cash at the caisse if they are not supposed to be.  What do you think?

**Comment by lomamech** [comment]
This option will raise both issues at the same time
