### ISSUE TITLE
Proposal: Restructure Posting Journal Schema

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#112]
This proposal concerns the MySQL tables `posting_journal` and `general_ledger`.
#### Motivation

There is no clear way to reference an invoice in the Posting Journal or General Ledger.  There should be an easy way to look up transactions in the database and following links between transactions to relate dependencies.  For example, a cash transaction may reference a previous patient invoice, or a stock increase may reference the purchase order's cash transaction.
#### Column Redefinitions

I propose that we drop the columns `doc_num` and `inv_po_id` entirely.  These will be replaced with more meaningfully named columns `record_uuid` and `reference_uuid`.  The `record_uuid` should be the  uuid of the table which posted the record to the posting journal.  For example, if it were a cash payment, it would be the `cash.uuid`.  For a patient invoice, the `sale.uuid` associated with that record.  This is a required field, and it will be the same uuid for an entire transaction.

The `reference_uuid` will reference other `record_uuid`s in the posting journal, forming the link between multiple transactions in a series.  One line in a transaction will never have a `reference_uuid`, but all other lines may have one or none.

~~#### Why two columns?
You could model the same functionality with a single column.  However, two columns also greater flexibility in application logic.  Two columns distinguish between the idea of an ID and a reference.  We can use this idea to build business logic that warns the user if they are deleting a transaction that is referenced in a subsequent transaction.  With a single column, you cannot be sure if you are deleting the ID or the reference.  With two columns, all you need to do is check the column name.~~

Interested in any feedback @IMA-WorldHealth/local-contributors.

**Comment by DedrickEnc** [comment]
@jniles 
- This solution will lead us to deal with many `uuid` as clause in our SQL queries since we are trying to avoid **abusive** `uuid` usage.
- We will have reference column `HBBXX` and `record_uuid` which are the same thing in terms of meaning, both of them are identifying the transaction.
- This situation will let us making join with columns which are not indexed since we are trying to apply and respect the database standard.
- With those two additional **uuid** not usefull to talk about time to request and get data because it is  trivial to guess that our general_ledger table will become heavy (**bad english sorry**).
- If we can not link receipt between them for now, we can a least make them very accessible by providing possibility to view the receipt wherever and easily.

**Comment by jniles** [comment]
- What is an abusive `uuid` usage?
- There reference column`HBBXX` is a TEXT.  Selecting on a binary uuid will be much faster for both the general_ledger and the posting_journal.  Our storage will increase by 32 bytes per line.

How do you propose to link/find a previous receipt from the posting journal?

**Comment by jniles** [comment]
Also, do you have an alternative proposal for the structure of the posting journal?  Are we just going to keep the useless `doc_num`?  What about `inv_po_uuid`?  What will be our policy to decide what goes where?

**Comment by DedrickEnc** [comment]
I agree that `doc_num` must be removed and we should find a mining-full name for `inv_po_id`.
In my knowledge, for now we are using `uuid` `char(32)` not binary `uuid`.
I have not a well defined proposal for the `posting_journal` table, but the `doc_num` can be replaced by `record_uuid` (**to have it in a binary form will be excellent!**), a `reference_uuid` can be handled at the low level, that means the entity him self must be responsible to keep is previous receipt.
E.g the `cash` table should have a reference for a `sale` table not the `posting_journal`.
So that from the posting_journal we can find the `record_uuid` which is the origin of the transaction and form the origin we can find the source.
This proposal is not the best but it is more balanced because it is sharing weakness of using uuid among many tables also it seems more logic because the posting_journal should only give information about is own origin.
If I find a new solution, I will let you know naturally.
@jniles

**Comment by jniles** [comment]
@dedrickenc, with @sfount's PR for the posting journal client core (#215) we should look at refactoring the journal's server side next.  Do you have an alternative design proposal for the journal table schema?

**Comment by DedrickEnc** [comment]
At the top of your last comment, I gave a proposal, since that I have never thought about this subject.
But now we have binary uuid, it means many things.
Thanks.

**Comment by jniles** [comment]
Okay, it sounds like we agree on `record_uuid`.  ~~I am not sure I understand what the origin lookup is, or how references work from one entity to another.  If you could clarify that by showing what the schema of the associated tables should be, it would help.~~

Edit: I understand the origin lookup now.  Here's what it would do:
1. Look up cash record in the `posting_journal`.
2. Look up cash record in the `cash` using `record_uuid`.
3. Look up `cash_item`s for `sale_uuid`.  Note that there is no 1-1 mapping between posting journal lines and cash_items, so this lookup isn't specific, since there is no id mapping posting_journal rows to cash_item rows.
4. Using the `sale_uuid`, lookup the `record_uuid` in the posting_journal for that sale.

I would argue that keeping it all in the posting journal is a more elegant solution, costing us only 16 bytes per record (with binary uuids).  It avoids JOINs and having to deal with a lack of ID between the cash_items and posting_journal tables.

I'll implement this proposal in a new PR this week so that we have binary uuids in the posting journal.  That will at least allow us to move forward with the posting process and more advanced e2e tests that tie together the sales and cash process.
