### ISSUE TITLE
(refactor) Standardise registry links

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1232]
Currently we have a number of different ways of performing actions on registry rows (double click, click link icon, etc.). 

I propose that we standardise this in a way that will allow users to always know what to try if they want to find more information about a cell. 

For users that are not advanced with computers a simple link is very easy to understand - an action like double clicking can often lead to surprise and there is no confirmation that that is actually what you want to do. (As mentioned and removed with https://github.com/IMA-WorldHealth/bhima-2.X/issues/1226)

However there are a number of different types of action that BHIMA could take on a cells data. The three I can think of are: 
* Open a modal (receipt) 
* Link to a registry 
* Link to a module (patient record) 

I think we need a way to differentiate these links so that it is very clear what will happen when a user clicks a link. 

My proposal is to add a muted icon in front of the cell to describe what will happen when this is clicked, for example: 

**Open a modal**
![screenshot 2017-02-20 at 18 10 12](https://cloud.githubusercontent.com/assets/2844572/23135328/6f6290b6-f798-11e6-83fb-c537470ff82e.png)

**Link to a module**
![screenshot 2017-02-20 at 18 10 24](https://cloud.githubusercontent.com/assets/2844572/23135331/745b50bc-f798-11e6-9f34-7e6c5f0d337a.png)

**Pros**
* Clearly demonstrates what will happen when you follow a link
* Can be used across all registries

**Cons**
* More expensive to render cells (icons, classes)

If anyone has any ideas or comments they can be discussed in this thread.

**Comment by jniles** [comment]
Looks fine to me.

**Comment by DedrickEnc** [comment]
The idea is interesting @sfount , from the pictures I can distinguish an icon for link and for modal that is mostly because I am advanced in using computer and internet (also because I read the issue first) so it is not necessarily the case for a user who is using the computer for the first time, distinguishing these kind of icon can be very tough for him.

An other concern is the quickness in audit or control so if you have many document to control or to view, it seems easy to double click all line at once without caring about a specific cell to get document view instead of clicking on a particular cell.

One of very good thing I can notice about android apps is the ability of being extremely interactif, if you press on an icon there is an action, if you maintain a press on an icon there is a different action that is what BHIMA should do by taking care that the user will not get confused.

I think double clicking the all line to get a document of the entity only is good because double click in user interface principle (or behaviour ... don't know the good word to use) means openning some thing so in our case a double click should show a document to let user having more details but we can also provide more options on the same line like you proposed which can be performed by a simple click.
Double click should be supported on all our registries, I think.

Sorry for this long text ...

**Comment by jniles** [comment]
At Vanga we are using laptops without an external mouse.  I have noticed that when users try to click the dropdown, they often double click and then open the receipt modal.  They then ask me for help.  I think that, while the double click makes opening a receipt easier, it makes other actions much more difficult.

What is your experience at Lukonga?  Have you seen users use the double click effectively?

**Comment by DedrickEnc** [comment]
That is a teaching concern and I think users can get used to this reality, at Lukonga we did not work on Saturday because the town was not safe, I was only with Jean. So today it rained all day so I will see tomorrow and tell you what.
