### ISSUE TITLE
(feature request) Caution refactor and tests

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1324]
There are a number of issues tracking the current implementation of cautions in 2.x. This must be corrected before releasing a solid financial base - many institutions rely on maintaining a line of credit with patients. 

Relevant discussions: 
https://github.com/IMA-WorldHealth/bhima-2.X/issues/808
https://github.com/Vanga-Hospital/bhima-2.X/issues/121
https://github.com/Vanga-Hospital/bhima-2.X/issues/34

**Comment by jniles** [comment]
I'll be tackling all caution-related work.

**Comment by jniles** [comment]
To summarize other issues here:

--------
Vanga-Hospital#121
Cautions have been a concept in 2.x for some time however there has only ever been facility to pay into a patients caution, crediting the patient and debiting a cash box. 

This proposal aims to: 
* Allow cautions to pay towards invoices 
* Reduce the number of complex corner cases to do with using cautions 
* Ensure users are very clearly notified about the state of a patients cautions 

The proposal is that the system implements the following rules: 
* **You cannot pay into a caution if you have remaining debt to the hospital** (This should be blocked with a clear modal explanation)
* **Any invoice made towards a patient with a caution remaining is directly linked and paid for by the caution** (This should be made very clear both on the invoice receipt as well as the user creating the invoice)

By implementing these two clear rules we guarantee that unless the accountant creates a specific voucher the system will not pay into cautions if the client has debt. This greatly reduces corner cases.

Required Infrastructure: 
- [ ] (MySQL) Patient invoice posting process uses cautions during the posting process (potentially as a separate voucher transaction)
- [ ] (Client UX) Invoices paid with a caution automatically very clearly mark that they have been fully or partially paid on creation
- [ ] (Client UX) Cash window blocks user from paying into a caution if the patient has debts with the hospital
- [ ] (Client UX) Reports/ views into caution payments, clear description in financial activity 

---

Required decision: 
Currently we can make this assumption because we do not allow the cash payment page to overpay an invoice. However this may restrict the user from recording what actually happened at cash payment. 

The current system: 
* Patient cannot pay more than the minimum currency unit above an invoice 

A proposal for how to deal with this is to automatically pay against all remaining debts given an over payment, after all debts have been paid any additional payment would go into the patients caution. 

The steps would be as follows: 
* Patient pays $20 to a $10 invoice, patient has another unrelated invoice for $5
* System puts $10 to the bill
* System puts additional $5 to reduce the unrelated invoice
* System puts remaining $5 into the patients caution 

This method lets us keep the guarantees about cautions and patient debt but also allows the cash box to record any money that they receive. 

In order to implement this the user interface/ rules for this have to made *very* clear to the end user. 

- [ ] (MySQL/ Client UX) Cash window provides modal for suggesting where over paid invoices can be allocated into other invoices/ cautions.
