### ISSUE TITLE
(performance) Investigate storing invoice balances in a totals table (Query Rank #1)

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1375]
```
# Profile                                                                                                                                   
# Rank Query ID           Response time   Calls R/Call   V/M   Item                                                                         
# ==== ================== =============== ===== ======== ===== ===========                                                                  
#    1 0x86863BB0CF7F56D2 4834.8091 34.2%   106  45.6114 22.87 CALL CalculateCashInvoiceBalances                                            
#    2 0x172C9AD568506549 2271.6316 16.1%    17 133.6254 15.85 SELECT cash voucher project debtor patient cash_box user                     
#    3 0x7146126EBA8A45BB 1906.9753 13.5%    78  24.4484 13.47 CALL PostInvoice                                                             
#    4 0x79B3A6B3AFBA6A34 1073.9583  7.6%  1059   1.0141  0.19 SELECT patient project debtor debtor_group village sector user patient_visit 
#    5 0x70FBFAE700A0D0C7  879.2873  6.2%   106   8.2952 82.17 CALL PostCash                                                                
#    6 0x9A1C8B26FB9FDA98  737.8403  5.2%    95   7.7667  0.13 SELECT UNION combined_ledger invoice project                                 
#    7 0x006CA608F6F95299  665.7194  4.7%   165   4.0347  0.28 SELECT combined_ledger document_map                                          
#    8 0x3183E320043295DC  445.9682  3.2%   116   3.8446  0.06 SELECT combined_ledger                                                       
#    9 0x6F6D9FDC88980472  229.7403  1.6%     2 114.8702  2.17 SELECT combined_ledger invoice voucher project                               
#   10 0x4E40D93B961475C4  228.1232  1.6%    79   2.8876 28.06 CALL WriteInvoice                                                            
#   11 0x04BEBBE2B4CDCF36  196.6480  1.4%    49   4.0132  0.14 SELECT combined_ledger                                                       
#   12 0xB97BDB4EDF4B0656  179.1795  1.3%    12  14.9316  0.04 SELECT debtor_group debtor combined_ledger                                   
#   13 0xAAA3A0523A8998D1  176.1755  1.2%    12  14.6813  0.05 SELECT debtor_group debtor combined_ledger account                           
# MISC 0xMISC              309.3979  2.2%  2030   0.1524   0.0 <58 ITEMS>  
```

From a review of our MySQL slow query log - the highest ranking query by far a call to `CalculateCashInvoiceBalances`. This method is only ever called during the cash payment creation process however it is responsible for **34.2%** of the MySQL processes time, with an average response time of over 5 seconds. 

This issue should be tackled on a number of fronts: 
1. Optimise the `CalculateCashInvoicesBalances` to reduce the stress and time required by this call, it currently uses `IN` vs. `EXISTS` for a query to the `combined_ledger`, this may be a good place to start. 
2. Store individual invoice balances in a 'Total' table, this would allow any methods to instantly look up the balances on any invoice. The following should be considered: 
  * Invoice balances must be recalculated on: invoice creation, cash payments, vouchers, posting journal editing 
  * utility tools for verifying all invoice totals are correct

**Comment by jniles** [comment]
Further information on WHERE analysis can be found here:  http://stackoverflow.com/questions/2246772/whats-the-difference-between-not-exists-vs-not-in-vs-left-join-where-is-null

**Comment by sfount** [comment]
Another suggestion for this issue from @WayneNiles is to have a table keep track of debtors with open debt/ invoices that have not been paid off. Doing this would allow us to only reference the open debt table when determining a balance instead of the entire combined ledger.

**Comment by WayneNiles** [comment]
ST implements two tables:

OpenDebitors

OpenCreditors

```sql
CREATE TABLE `opendebitors` (
     `CompanyID` INT(10) UNSIGNED NOT NULL,
     `DebitorID` VARCHAR(25) NOT NULL,
     `InvoiceNumber` INT(10) UNSIGNED NOT NULL,
     `AccountID` VARCHAR(25) NULL DEFAULT NULL,
     `AccountYearID` INT(10) UNSIGNED NULL DEFAULT NULL,
     `Credit` DECIMAL(19,4) NULL DEFAULT NULL,
*    `Currency` VARCHAR(8) NULL DEFAULT NULL,
     `Debet` DECIMAL(19,4) NULL DEFAULT NULL,
*   `Note` TEXT NULL,
*    `PayDate` DATETIME NULL DEFAULT NULL,
*    `PaymentID` INT(10) UNSIGNED NULL DEFAULT NULL,
     `Text` VARCHAR(100) NULL DEFAULT NULL,
*    `Type` VARCHAR(8) NULL DEFAULT NULL,
*   `ValueCredit` DECIMAL(19,4) NULL DEFAULT NULL,
*    `ValueDebet` DECIMAL(19,4) NULL DEFAULT NULL,
     `VoucherDate` DATETIME NULL DEFAULT NULL,
*    `VoucherNumber` INT(10) UNSIGNED NULL DEFAULT NULL,
     `DDFNumber` INT(10) UNSIGNED NULL DEFAULT NULL,
     `Ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE 
CURRENT_TIMESTAMP,
     PRIMARY KEY (`CompanyID`, `DebitorID`, `InvoiceNumber`),
     INDEX `AccountID` (`AccountID`),
     INDEX `DDFNumber` (`DDFNumber`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```

Starred lines are actually not used and working with debts across 
currencies over time is hairy as you know.  The Currency and Value 
fields would be used if you are trying to track across currencies.


Updating the table is a simple insert from a groupby query

BEGIN
DELETE FROM OpenDebitors WHERE CompanyID = CompanyIdVal;

INSERT INTO OpenDebitors (
      DebitorID
     ,InvoiceNumber
     ,AccountID
    ,VoucherNumber
     ,VoucherDate
     ,AccountYearID
     ,`Text`
     ,Debet
     ,Credit
     ,DDFNumber
     ,CompanyID
     )

SELECT TR.DebitorCreditorNumber
     ,IFNULL(TR.InvoiceNumber,0)
     ,TR.AccountID
     ,TR.VoucherNumber
     ,MIN(TR.VoucherDate)
     ,TR.AccountYearID
     ,TR.`TEXT`
     ,Sum(TR.Debet) AS SumDR
     ,Sum(TR.Credit) AS SumCR
     ,IFNULL(TR.DDFNum,0)
     ,TR.CompanyID

FROM Transactions AS TR
WHERE (
         (TR.CompanyID = CompanyIdVal)
         AND (TR.DebitorCreditorNumber IS NOT NULL)
         AND (TR.DebitorOrCreditor = "D")
         )
GROUP BY TR.DebitorCreditorNumber
     ,TR.InvoiceNumber

HAVING (abs(Sum(TR.Debet - TR.Credit)) > OpenDebitorsDiff)

ORDER BY TR.DebitorCreditorNumber
     ,TR.InvoiceNumber;

END

Note that OpenDebitorsDiff is a configuration limit to ignore 
differences below a limit.  Most of my accountants keep that value at 
0.  When I made it >0 one accountant kept track of a $5.36 discrepancy 
across ALL invoices between the GL and opendebitors because they had to 
have everything balance.

The opendebitors table is then used to generate all kinds of debtor 
reports including the aging one.  You never have to query the GL.

Occaisionally the table total does not equal the periodtotals total for 
the accounts hit by the various account groups that the debtors are 
members of.  So you do a refresh from the GL.   As commented on Git the 
table needs refresh on posting, payment of invoices, creditnotes, etc.

**Comment by jniles** [comment]
OpenDebtors is not actually what we want for this particular case  - it would be OpenInvoices.  BHIMA keeps track of the debt due on each individual invoice rather than the debt due to the debtor in total.

An OpenDebtors table will definitely help with other queries though - it's a fine art of trying to figure out when you have too many aggregation tables.

**Comment by WayneNiles** [comment]
Only one debtor per invoice, hence the basic unit of info is the couple 
debtor-invoice.  Filter on debtor and you necessarily filter invoices, 
or vice versa.  An openinvoices table would match row by row to an 
opendebtors table.

Wayne

**Comment by sfount** [comment]
This was addressed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1403 as is no longer found in the top slow log queries. The analysis can be found here https://github.com/IMA-WorldHealth/bhima-2.X/pull/1403#issuecomment-288388256
