### ISSUE TITLE
Implement User Roles

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#170]
#### Motivation for Roles

In most applications, there is some management of user groups, usually based on sets of permissions.  In the most limited form, this can be a simple separation of "administrators/super user" (complete read/write/modify access) roles from "regular user" roles (limited read/write/modify access).  In more complex cases, mixed groups of permissions can be assigned to particular roles, such as "Logistician", "Accountant", or "Pharmacist".
##### Motivation for Changes

The current permissions in bhima is fundamentally broken.  There are a number of problems with it:
1. Permissions are view-only: they only affect the client-side view.  Any logged in user can send whatever POST/PUT/DELETE requests they want to the server from the console and completely destroy the database if they know how.
2. Permissions only affect the tree.  If a user knows the URL of a particular module, they have complete access to it.
3. Permissions are binary.  A user either has complete access to a module, or no access.  This makes it impossible to create a user that is a "read-only" user, for example.
##### Proposed Changes

Given the issues discussed above, I propose the following changes to permissions that will allow us to create powerful user roles. 

I would like to see user roles implemented in bhima that are able to control not only _access_ to modules, but also permissions within modules.  I can see each module having at least three permission levels:
1. `read` - The user is able to access the module and view the contents (like an SQL `SELECT` statement).  However, the user will not be able to modify the information inside in any way.
2. `write/modify` - The user has `read` permissions, and is able to `UPDATE` and `CREATE` records.
   3.`delete` - the user has both `read` and `write/modify` permissions, and is able to `DELETE` records from the application.
##### Implications on the Client

For the client, this proposal is not achievable with the current router (`ngRoute`).  I believe it is achievable with [ui-router](https://github.com/angular-ui/ui-router).  It will also require that our pages be designed to support a user with limited permissions.  A read-only user should not be presented with the option to delete or modify records.  A superuser should be able to access all functions of a module.  It should not be possible for a read-only user to gain super-user privileges by typing in the URL or editing the HTML.
##### Implications on the Server

Because bhima is using a client-server architecture, any implementation will have to limit both the view and affect the data the server sends back to the client.  For each module, if the user does not have the appropriate permissions level, the server must respond with a `403 Forbidden` API error message.
#### User Roles

Designing and implementing roles is a complex task.  If we allow users to have fine levels of permissions as proposed in this issue, it will become very easy to allow users to create new roles dependent upon their institution's policy.  We might include a few basic roles ("Super User", "Chief Accountant", "Head of Logistics", "Pharmacist", "Receptionist", etc), but most the roles will be created when an institution adopts the software and begins to define roles for its users.
###### Initial Thoughts on the Schema

A "role" will be a `label` and a collection of modules and permissions associated with those modules.    We should discuss the SQL implementation further.  One idea might be to have the `user` table contain a `role_id` mapping to a `role` table.  The `role` will contain an `id` and a `label` column.  A third table, `access` (needs a better name) will map `role`s to `unit`s with one of the permissions levels described above (`read`, `write/modify`, `delete`).
#### Conclusion

This proposal is an ambitious redesign of the users and permissions to support maximum flexibility.  This design should be refined with feedback and motivate alternate proposals.  If we implement something similar to this, we should be able to account for the organogram of virtually every institution.

**Comment by imawh** [comment]
Roles are **Essential** in any software the size of Bhima

In SanruTracker we give each person permissions individually.

There's a lot of repetition, since there are lots of accountants, senior accounts, logisticians, etc.
Providing the individual permissions to one of 35 forms, etc, is bothersome.  Creating ROLES removes some of these repetitions as you can define the privileges of a junior accountant and then assign 2-3 people to that role.

In bhima, obviously you will have lots of roles: nurse, doctor, junior accountant, senior accountant etc and in a large hospital you will probably have lots of people in each role.  So rather than give permissions to individuals, you give permissions to Roles and then assign people to these Roles.  Just an extra layer of abstraction to simplify permissions management in a large institution.

In SanruTracker we have several levels of permissions (but no roles yet):
1. Project level - in Tracker each project is it's own universe with chart of accounts, debtors, creditors, debtor groups, inventory etc.  A person with access to only one project never ever even sees the other projects, they work in their own universe.
2. Form level - All projects can use all forms but not all users can access all forms.  Logisticians never see any accounting forms in their menu tree so they can't open them.  The main way of giving permissions in Tracker is what forms a person can access. 
3. Special, in-form behavior.  During form loading, Tracker may add or enable buttons, drop downs, etc based on the user's permissions.  For example, a Senior Logistician may notice a Logistician has created two Destinations for shipments: CRSKindu and KinduCRS.  When a Senior Logistician looks at the Destinations form, he/she sees a **merge** button that a junior logistician does not.  The senior logistician may then merge all instances of KinduCRS into CRSKindu which in Tracker means updating 8 different tables (detail rows of shipment and bons de sortis and others).  Obviously whoever does a merge needs to know what they are doing.

Project access and Form access is implemented in a many to many table (one for project, one for forms).  Just three fields, projectid,userid, accessYN.  Only the trues are stored.  Similar for Forms, formid, userid, accessYN

To implement roles, you would substitute roleid for userid and then have a table describing roles, and their id's.

In WebERP and Care2x roles resolved to numbers.  Lower numbers have greater permissions than higher.  I would design roles with 3 digits at least so accounting would be in the 200's, Logistics in the 300's, Admin in the 100's and SuperUser would be 1 or 0.  Would need to think the queries through so how would you manage to control for 3 levels of accountants.  "If roleid >= 230 then ..." might give permission to 220 and 210 roles (and all of Admin as well).  When you get into managing patient records you will have doctors and nurses poking around patient's charts and you want to be able to manage that carefully.

MySql grants permissions to tables and columns and to functions (create, delete).  Large accounting software goes even farther often applying filters to roles so accountants can see only some of the general ledger (hiding payroll for example).  Hence I doubt your first implementation of roles will be the final.  Get one functional and later on you will have to improve it, hopefully with out rewriting the whole back end.

[edit] light formatting.

**Comment by DedrickEnc** [comment]
So as a consequence
1. The user and the permission will not be linked directly. But they will be through the role. 
2. The user can not exist without a role so a role can contain no user
3. Investigation is necessary to decide how to deal with the user role at the server side, may be the choice is between giving this responsibility to the database and implementing an API directly in node to manage it.
JAVA Enterprise Edition deals with this concept of user role, I will seen how they do may be it will give us inspiration.

**Comment by jeremielodi** [comment]
I have already worked on some thing like this in one of my applications and I think with the current permission structure of bhima I can contribute.
In my application, I first create pages (bhima's permissions),
after I create roles, and I affect pages to each role
finally I affect role to the user

**Comment by jniles** [comment]
Go ahead and give it a try!

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2461 and further discussion moved to https://github.com/IMA-WorldHealth/bhima-2.X/issues/2665
