### ISSUE TITLE
(bug) Uploading document file types 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#1823]
This bug was submitted to the BHIMA `support@bhi.ma` thread. 

**Problem Description**
> I used bhima on my phone and took a photo but could not get it to save in bhima.

> I also tried to upload photo in bhima in windows using google chrome
and still got the same error.
screen shots attached.

> priority: Low.  nice feature that can be used occasionally.  It
might be used when we have people showing us their insurance cards so
we can take their photo for future comparison to their insurance card.

1. It looks like the file type of the image on phones is not supported by the document or patient image upload - this file type/ corner case should be considered.

2. **The logic for which file types are supported should be clearly documented in the code and clearly presented to the user**

3. The error responses for file uploads to not have correct translation keys to reflect what the issue is - this can result in a generic `Bad Request`. This is not a good user experience and should be refactored.

**Comment by jniles** [comment]
I propose the solution be that we simply limit the size of the file instead of the file type.  I believe the filetype is only detected via an extension anyway.  If, for some reason, the hospital wants to attach an X-Ray image to a patient via a proprietary format, they should be able to do that.

@IMA-WorldHealth/bhima-core what do you think?
