### ISSUE TITLE
"Rapprochement" button is hidden

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1945]
The rapprochement button in the posting journal is hidden for the user

**Comment by Scholldier** [comment]
Is the desired goal here to show a reconciliation button, or hide one that exists? Is the posting journal the Journal? Is the reconciliation button the trial balance validation?

**Comment by jniles** [comment]
Hey @Scholldier,

Sorry for not being more responsive!  The desired goal is to make the "Trial Balance"/"Rapprochement" button easier to use by moving it from the dropdown menu to the top bar.  Since accountants should be clicking this button multiple times a day, it makes sense to optimize the workflow.

[This is the link/button in question](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/journal/journal.html#L38).  We should make it more like [the other buttons outside the menu](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/journal/journal.html#L63).

One thing to think about: screen real estate is a premium - we have some users with 800x600 screen resolutions and the buttons behave all sorts of strangely on a screen of that size/resolution.  One idea might be to swap the "comment" and "trial balance" buttons, putting "comment" in the menu.  If you can prototype that, we can see how that works for us.
