### ISSUE TITLE
fix(simple voucher): the use of scanner for prise en charge decrease performances

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#1959]
The use of the scanner for prise en charge decrease the performance of the system others users.

It works fine before 8 A.M. before others offices start working with BHIMA

**Comment by jniles** [comment]
This issue has been reported before, but honestly doesn't make any sense to me.  Do you have any ideas why this might be the case?

**Comment by mbayopanda** [comment]
This issue has 3 basics points of view : 
- the user interface with the hidden input is not user friendly when the hidden input loss the focus
- the network was not good for performing task with the bar code scanner
- the query for scanning "Prise en charge" is slow and combine it with bad network the result is not good

For any solution which can help to fix this issue we can close this issue, the solution can be with network infrastructure, user training or coding.

**Comment by jniles** [comment]
I'll take a look at implementing a reliable component for barcode scanning.

**Comment by jniles** [comment]
So, while working on #2630, I think I may have fixed this.

One of the things I noticed is that reading barcodes would randomly return capital or lowercase letters for the identifier.  [It is now forced to be uppercase](https://github.com/IMA-WorldHealth/bhima-2.X/pull/2630/files#diff-874013b9514a97baf092c6e52fc34e5cL39) since that is what the identifier lookup is expecting.

Since this issue is unclear about the problems and proposed solutions for the barcode scanning, I'm going to optimistically close this.  Based on user feedback we can reopen this if problems persist.
