### ISSUE TITLE
Deep Refactor of the server side code and Structure

### ISSUE THREAD

**Issue by DedrickEnc** [third-culture-software/bhima#2054]
I took the time to see our server side code and structure, I have noticed that it needs a deep refactoring and restructuring.
I propose to make our code more modular and easy to read, even if it is not a high priority. 
An organisation where we have one main express application (**bhima** or **app**) and a set of sub express applications around (admin, hospital, finance, stock, payroll ...) representing modules that we have in the system.

So, I propose the following architecture for our server : 
![main server architecture](https://user-images.githubusercontent.com/5418919/29709923-2ffb40d2-8986-11e7-8a4b-db7b112ec278.png)

Notice that, the main server application is a single file, witch mount the whole bhima system, and will perform the following tasks : 

- Creation of the main express application (M.E.A)

- Configuring middlewares

- Loading all needed sub express applications (S.E.A)

- Setting some behavior on the process object (the node process object)

Note that with this architecture, we can also build a generic web server which will mount and host web application by adding one more level to the express application hierarchy and considering bhima express application as a sub express application which must be mounted (many consideration must be taken in account : **security, port management, middlewares using ...** this is not our case).

Here is now the sub express application organisation
![sub express app archictecure](https://user-images.githubusercontent.com/5418919/29712714-1c3b9058-8993-11e7-860d-811a66067c3f.png)

The interaction between the main express application (M.E.A) and a sub express application (S.E.A) can be seen like : 

**Step 1**

- The M.E.A imports a S.E.A class

- The M.E.A creates an instance of a S.E.A class

- The M.E.A mounts S.E.A by calling the publish method of S.E.A object.

**Step 2**

- On the publish method call, the S.E.A publishes an express application to be mounted.

**Desavantages:**

- This work is so huge and will need time to be done

- Team member will need time to get used with the new structure

- Some of our tests must be reviewed.

**Avantages:**

- The entire code at the server side, will be easier to read because they will be broken up into small files.

- Modular programming

- Dependencies will be easily identified and used

- Make the code re-usability easier

- Intensive use of O.O.P

- Make the code review easy because most of code should be written once and reused a lot

- The decentralized way of managing server routes

- The main server easy to understand and to maintain because it will be seen as a collection of middlewares and sub express applications.

N.B : 
An express object can listen to an event called ```mount```, in that way :
```
app.on('mount', function (parent){
console.log('the sub application is mounted to the ', parent);
});
```
we can use this to expose routes of a S.E.A only when it is mounted to the main application.

Sorry for this long issue

@IMA-WorldHealth/bhima-core 
Any thought?

**Comment by jniles** [comment]
Hmm...  I do agree that we can do a lot better in the architecture of our application.

We should probably choose an existing pattern, rather than invent our own.  [There](https://blog.ragingflame.co.za/2015/4/1/how-i-build-nodejs-applications) [are](https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/) [a lot](https://medium.com/@gwilakers/structuring-your-node-js-app-67d20c2ab8a3) [to choose from](https://seanmcgary.com/posts/how-to-structure-a-nodejs-express-project).

In my mind, the best place to start is by refactoring our routes.js into smaller routes files specific to finance, inventory, etc.  We can do this even without creating sub-applications, just by using `require()`s.  Once that is complete, we will be able to understand which sub-applications need to exist, since the code will already be separated out.

Since we haven't done any unit testing of the server, this refactor shouldn't affect anything with tests, actually.  Which is the beautiful thing about tests :+1:

**Comment by DedrickEnc** [comment]
[here is an example](https://github.com/DedrickEnc/modularExample)
