### ISSUE TITLE
Add depot permissions for user

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2171]
This issue is about the add depot's permissions to user, such as for projects

The user must be able to perform stock operations (entry or exit) just in depots in which is authorized (has permissions).

The proposal is : 

1. Add input for depots in the user management module such as for projects
![edit user](https://user-images.githubusercontent.com/5445251/31016256-dfc98748-a51b-11e7-90a0-b68521994ab9.png)

2. Depots loaded in each module of bhima must be just authorized depots for the connected user

**Comment by jniles** [comment]
This is an interesting idea. By the same logic, we could also limit cashboxes.

I wonder whether this would be a good thing or a bad thing overall.  I can see it going both ways - limiting a user because they are not properly logged it, or making it difficult to add staff ... or limiting the number of errors.   It might be worth a try!
