### ISSUE TITLE
Installation feature for bhima

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#2299]
This issue is about to have an installation feature in bhima, when we want to initialize bhima for a particularly institution this feature will help by :

- Allowing to create a super user for bhima, define enterprise information (name, abbreviation, currency) and define also the initial project of the enterprise.

For having this feature, the proposal is : 

1. To have a route `/install` which help us to check if the application is already installed and also to run other installation scripts

2. On the client side, we define a particular route for the installation page. When there is no installation we can access to installation page, but when the application is already installed this route on client will redirect us to the login page or display a message (need discussion).

Having a page in the client side is important because it can help us to enhance this feature with accounts import, inventories import, etc.

This issue is about a first implementation, which suppose that before install the application via the installation module the database  must be built with basic information (the database will allow us to check also if bhima is already installed)

Feel free to give your suggestions 😃

**Comment by jniles** [comment]
It seems to me this can be broken down into the following steps:
 1. Create the Enterprise (and defines the default currency)
 2. Create one or more projects.
 3. Create one or more users.

One question is ... should the app simply cache these values until the very end of the process and then click "Write values and complete" or should it write the values at the end of each step?  I'm in favor of the first, since it will be easier to detect when the database is in an undefined state.  It's an "all or nothing" approach.

**Comment by jniles** [comment]
Closed in #2304.
