### ISSUE TITLE
Setup Problems

### ISSUE THREAD

**Issue by jmuzsik** [third-culture-software/bhima#2581]
Hi, well, I've been working on getting it set up for some time and this is where i'm at this moment:

First, forking/cloning and ``` npm start/bower install ``` 

Then I ran ``` ./sh/build-development-database.sh ```(this is different then in the README as in: development rather then developmental). After running it several times I realised that I need to go into the env.development file to alter DB_USER and DB_PASS.

Some errors that may relate to the final error:

<img width="1280" alt="screen shot 2018-03-03 at 16 26 07" src="https://user-images.githubusercontent.com/29470576/36939729-0c63617c-1f04-11e8-9d9d-873214e0d18e.png">

Notice two files are missing that are called in the shell script and the is_asset problem.

After I ran ``` npm run dev ```which gave me this error: 

<img width="1280" alt="screen shot 2018-03-03 at 16 27 20" src="https://user-images.githubusercontent.com/29470576/36939750-aca1f5b8-1f04-11e8-9cb6-546df1bf369d.png">

In which case I had to do an action that was not idea ( commenting out what process.env.NODE_ENV was equal to and making it equal to 'development') because NODE_ENV was not set prior:

<img width="1280" alt="screen shot 2018-03-03 at 16 32 22" src="https://user-images.githubusercontent.com/29470576/36939761-d9c3feb0-1f04-11e8-922f-e925b95f21ef.png">

Then ```npm run dev``` gets me to localhost:8080 but now there is this error that I am unsure how to respond to.

<img width="1280" alt="screen shot 2018-03-03 at 17 18 12" src="https://user-images.githubusercontent.com/29470576/36939901-e7ecf058-1f06-11e8-8c0d-694be7c141bf.png">

I honestly barely know where it is I ought to look in this case. I was searching here and there but quite obviously there is a core problem here that I am not seeing. It does not help that I can barely read AngularJS, I know Angular 5 some but not AngularJS. So I do not know what leads to what.

Is there something I should try to do, or a fundamental wrong action in my setup?

**Comment by jniles** [comment]
@jMuzsik, sorry it has taken so long to respond to this.

There are a couple of things going on here, it looks like:
 1. The command `./sh/build-development-database.sh` isn't quite right.  It should just be `./sh/build-database.sh`, as this will build the initial test dataset.  The `./sh/build-development-database.sh` command attempts to build an outdated demonstration database.  We should probably just remove it at this point.
 2. Well done! The NODE_ENV should be set to `development`.  This is often done via an environmental variable - it looks like [this line](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/package.json#L8) isn't behaving how it was intended.  I'll fix it in a subsequent PR.

Finally, the console errors could be anything tied to the above two.  I suspect the MySQL database is empty (due to running the wrong `build-development-database.sh` script) and that is causing the `user` table to not be populated.   By rectifying that, perhaps we'll get more insight?

**Comment by jniles** [comment]
@jMuzsik, did these instructions help?  We also have more detailed instructions in our [manual](https://manual.bhi.ma/for-developers/for-developers/installing-bhima.html).

**Comment by jmuzsik** [comment]
@jniles Hi, I'm sorry but have been very busy as I am looking for a job right now. I want to go back to this soon though. This project has a lot of meaning to it so I'd like to help out in the future. Thanks a lot for the thoughtful explanation.
