### ISSUE TITLE
(Proposal) Patient Overview/ Record Module

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#278]
This subject was briefly discussed in the design discussion [here](https://docs.google.com/document/d/1P4bzrMq8KQfawn3TqobJZ3_9ear6KomaQS8RJI_PNok/pub). 

The focus is to ensure that BHIMA supports everything that is required by the patient entity without creating an explosion of modules to maintain. 

The proposal is as follows: 

**Patient Registry**
Records of all patients registered in the system, from here users can search/ sort/ filter patients - anything to do with looking up a patient. 
This central record of a patient (a row in a table) also links to/ facilitates: 
- Patient Overview (Record) for each patient
- Check in the patient (to be fully specified) 
- General patient reports/ views

**Patient Overview (Record)**
- View all of the patients information/ attributes 
- Print ID cards
- Edit the patient (potentially through a separate UI-router state incorporating the current patient edit page)
- View patients financial history and debts 
- Attach patient files/ documents to this patient 
  
  ![patient overview](http://i.imgur.com/8KzrHzM.jpg)

**Comment by jniles** [comment]
Related to #63

**Comment by imawh** [comment]
RFID chips?

**Comment by jniles** [comment]
Closing this as completed, since almost all the pieces are there.

As noted in #477 and #452, there is a question of whether to use `ui-router` or components to fit data into frames.  Once the team chooses an implementation, we can finalize the patient activity panel and patient events.

Future directions mentioned here, but not (so far) within 2.x's scope are:
1. Barcodes/QR codes
2. SMS contact information
3. Patient Notes

These will require proposals before they can be implemented in 2.x.
