### ISSUE TITLE
Accounts seems to be hit a lot!

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#2892]
It looks like our HTTP requests seems to be hitting the `/accounts/` route a lot!  We should see if there is any way to reduce these requests - from my naive guess, the following screenshot was taken from the stock module.

![accountshitalot](https://user-images.githubusercontent.com/896472/41601257-3cd6f214-73d8-11e8-9948-c4587fbfefbd.PNG)

**Comment by jniles** [comment]
One potential solution would be to debounce the $http request by something like 100ms.  We could use the [angular-debounce](https://github.com/rubenv/angular-debounce/blob/master/src/debounce.js) library to do that for us.

Note that, if we did such a thing, it might affect how our unit tests go.  We would need to make sure the debounce library was properly flushing during unit tests to have the same behavior.

**Comment by jniles** [comment]
I'll tackle this one, since I am on a performance kick. :soccer:

**Comment by sfount** [comment]
@jniles you just beat me to it! I haven't started yet though so all yours. 

At one point there was an effort to use client side 'Stores' that could be shared across components and only make a request if they didn't yet have data available, I wonder if something like that would be useful. The main consideration with that would be when is it appropriate to invalidate data and check again. 

This looks to me like component initialisation requests that make fresh requests on initialisation and aren't aware of any other component.

**Comment by jniles** [comment]
Yeah, I'm almost 100% sure that is the issue as well.  [Check this line out - it creates 300 bhAccountSelect components](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/modules/vouchers/complex-voucher.ctrl.js#L128).

I'll have a PR in under an hour that you can look at to see how it does.

**Comment by sfount** [comment]
@jniles I've just had a follow up thought on this. In cases like you have demonstrated/ linked here the reason so many requests are made is because the account component is responsible for fetching its own accounts and we are not always careful about where we place it. 

What if we gave the component a `fetch` binding as experimentally implemented on `bh-user` in https://github.com/IMA-WorldHealth/bhima-2.X/pull/3121. 

On large complex pages that know there will be hundreds of component instances the programmer could simply prefer 
```html
<bh-account-select accounts="MyCtrl.accounts"></bh-account-select>
```

Over: 
```html
<bh-account-select fetch></bh-account-select>
```

Potentially the ideal end solution involves client side caching and TTL etc. however this might be a good middle ground, it leaves the controller developer more responsible but would limit one module to one request.

**Comment by jniles** [comment]
@sfount good suggestion!  The simplicity of a fetch tag is probably better than the complexity of what I was working with.  The downside is that we then have to identify all the areas where accounts is hit a lot and make sure we manually manage the accounts `read()` call.

I'll take a look at incorporating these ideas and see how they work.  On the short term at least, this will relieve some pressure on the heavily used pages.
