### ISSUE TITLE
Design login and client session 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#292]
There are currently [many bugs](https://github.com/IMA-WorldHealth/bhima-2.X/issues/286) on the login page to do with user sessions. 

These should be tackled with a design proposal for the login page: 
- End to end tests proving all of login works 
- Unit tests validating individual services and controllers 
- Proposal for login session design - how is this shared amongst all components that need to know when the user has logged in and logged out

The development of the login page is tracked here https://github.com/IMA-WorldHealth/bhima-2.X/issues/222; this design should specifically be for sharing the login/ logout activities safely with all required components as well as testing different use cases; access to forbidden files, logging in and logging out etc.

**Comment by jniles** [comment]
I'm closing this as addressed in #245.

The `SessionService` now emits `login`/`logout` events that can be hooked in for components that need to know of the application state, such as the tree.  [Here](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/src/js/services/session.js#L84) is a code reference, and [here](https://github.com/IMA-WorldHealth/bhima-2.X/blob/master/client/test/unit/services/SessionService.spec.js#L75) is a test showing expected behavior.
