### ISSUE TITLE
Design: make corrections of posted records easier by adding "reverse" and "correct" actions

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3063]
The point of the unposted/posted dichotomy is to have correct data validated and verified for reports.  Unfortunately, bad data is still posted and needs to be corrected.  The proper way to correct the transaction is to reverse it, then recreate it with the correct values/accounts/currencies/etc.

When you actually try to correct a transaction, there are a lot of steps involved.  We should make this process easier.  I propose a simple(r) way to make changes to posted data, while still maintaining the paper trail, by either "reverse"-ing or "correct"-ing a previously made transaction.

**Design**
For unposted records, we provide the user the opportunity to "delete" records using a delete button on the transaction modal.  You can see that below:

![deletebuttonontransactionedit](https://user-images.githubusercontent.com/896472/44406768-59f71100-a554-11e8-8f4b-b6fabcf00f9e.PNG)
_Fig 1: Delete button on Transaction Edit Modal_

For posted records, this button is hidden.  I propose that we replace the "delete" button with a button group containing "correct" and "reverse" options.

Once a user clicks the "correct" button, the values in the transaction will be unlocked (as if it was unposted) for correction.  After the user makes adjustments, they will submit the modal.  When the user submits, the following things take place:
 1. The system creates a second, reversing transaction that annuls the first one.
 2. The system creates a third transaction based on the data in the transaction and the modifications the user had made in the edit modal.
 3. Both records will be written first as vouchers, then added to the journal via the `PostVoucher()` stored procedure.  They must be manually posted by the accountant to take effect as an additional verification step.

We would need heavy testing of the transaction edit modal for this to work effectively.  I'm not sure it is well tested at this point.

**Comment by sfount** [comment]
@jniles this is a well written and clear proposal! I have some thoughts on the concept and the execution: 

Considering behaviour - because everything is done through additional vouchers this shouldn't have an unknown effect on reports like unposting and posting would have (something that we may need to consider with super administrative privileges). 

From that perspective this should work fine, however making it more routine/ simpler to correct generic transactions brings up things that we never fully considered, one of which is the relationship between underlying BHIMA financial documents and their financial equivalents in the journal. The benefit of performing these tasks on the entities themselves (like credit notes for invoices, reversing cash payments etc.) is that we can make it clear to the user what happened on the receipts/ registries etc. 

Potentially we could investigate having a generic `manipulated` flag on core financial entities that would allow us to put a disclaimer throughout the UX that this document may no longer reflect exactly what was originally produced. 

Whether that makes sense or not I think this feature could save a significant amount of time for administrators and may even be make or break for running in production so I think work on it should continue. 

My original thoughts about the system flow would be something like: 
* User clicks to edit  a posted/ finalised transaction 
* User clicks reverse 
* A separate tool is opened (to keep the code and the ideas separate) and preloaded with the transaction that was selected
* This administrative tool clearly shows the steps it is going to take to reverse the transaction, essentially as a check list: 
  * Create a voucher with equal and opposite lines 
  * (If edits applied) Create a voucher with new values provided from the edit modal
  * All approved by (the current user name) 
* Clicking submit would then make server requests for each of these actions, I think it would be a clear UX to then update each of the lines with clear references to the vouchers that were just created as well as a confirmation message that everything was successfully written

I'm not sure if this lines up with what you were thinking, let me know and I'll continue to consider the implications of these features.

**Comment by jniles** [comment]
@sfount, thanks for your feedback on this proposal.

Your `manipulated` proposal is intriguing.  We already have "edited" and "reversed" flags on each record table (`cash`, `voucher`, `invoice`).  What would the `manipulated` add that is different than those two?  It seems like they should be enough to cover all states so far, no?

I like the idea of listing out steps - the more clearly we can convey the operations to our users, the better!   Using the same interface was appealing to me since it is a reduced maintenance burden ... but it's a serious enough operation that we should probably clearly separate it from routine editing tasks.

**Comment by sfount** [comment]
I'll look into starting development on this feature, it may take a few pull requests and iterations to get right. 

Tentatively it could be ready for the first round of user testing by the end of this week, it would be great to make sure that the paper trail/ process it follows is verified and signed off on by an accountant who also understands the UX.

**Comment by sfount** [comment]
@jniles I'd like to run the current UI/ UX/ implementation decisions on this issue by you before finalising the feature structure and continuing development. Pair programming remote style. 

The focus has been how to implement to find the balance between not adding huge amounts of code to maintain and not keeping the user completely in the dark (for example; `reverse` button performs server side action, completes and closes modal). 

Current proposal outline: 
* Introduce the concept of **'Voucher Tools'**, these are a collection of components/ services/ server API that exist to automate common financial transactions by creating vouchers 
* Voucher Tools have three stages, input (usually from module controller) , processing (generally should all happen in a transaction on the server) and output (reflect to the user what happened) 
* The reverse tool was implemented in the 'Transaction Edit' modal
* An inline component was used to try and find the balance between creating entirely new modules/ modals and just showing the user a quick notification

Changes required for transaction edit modal: 
```html
<!-- Must include the relevant voucher tool -->
<bh-voucher-tools-reverse
  ng-if="Ctrl.isReversing"
  source="Ctrl.transaction"
  show-badge>
</bh-voucher-tools-reverse>
```

The `<bh-voucher-tools-reverse>` is added to the modal body and has the input phase: 
![voucher-tools-interface](https://user-images.githubusercontent.com/2844572/45163356-2ff64d80-b1e8-11e8-90cc-ba0b66a4d058.png)

The component handles thrown errors *internally*, that means that if something goes wrong it can gracefully fail:
![voucher-tools-multiple-cancel](https://user-images.githubusercontent.com/2844572/45163459-616f1900-b1e8-11e8-8f48-996c45b69e17.png)

Because the error handling uses the standard BHIMA format, the component will handle any additional error that BHIMA is familiar with if it happens because of the components actions: 
![voucher-tools-no-network](https://user-images.githubusercontent.com/2844572/45163566-8b284000-b1e8-11e8-846a-48f8940c8ee3.png)

If the server API succeeds, the component will transition from the input state to the complete state: 
![voucher-tools-success](https://user-images.githubusercontent.com/2844572/45163600-a004d380-b1e8-11e8-8ba4-4cc7bbfa0b1b.png)

This provides details on the actions taken by the tool and has a link to the created voucher. 

The component is integrated in the transaction edit modal, it is only included (`ng-if`) if the controller sets the value `isReversing`; for context: 
![voucher-tools-edit](https://user-images.githubusercontent.com/2844572/45163697-db070700-b1e8-11e8-8fb6-0073e171771a.png)

Notes: 
* All of the 'reversal' processing happens within the component, the outside controller does not understand what that means, it just passes in a transaction

I'm interested to know what you think of this design pattern. Any and all of these decisions are flexible and can be changed at this point! We were aiming for an end of week close on the first version of this feature so I will continue as soon as you've given the :ok_hand: .

**Comment by sfount** [comment]
@jniles now with flourish: 
![peek 2018-09-06 15-47](https://user-images.githubusercontent.com/2844572/45165270-63d37200-b1ec-11e8-96a0-f77998ea56cc.gif)

**Comment by jniles** [comment]
@sfount, thanks for the clarification and the easily understood issue.  Beautiful. I think this is a fine first implementation.

The only potential issues I can see is the modal overflowing small screens.  But we can worry about that later, in my opinion.  Let's build it and get client reviews first.

**Comment by sfount** [comment]
@jniles thanks for the feedback, well received! I'll make sure to test it with lower resolutions and will update this thread with progress.

**Comment by sfount** [comment]
Updating with the latest development on this feature: there are some tests and corner cases to round out but hopefully this can be pushed today in order to land user feedback this week. 

**Reversal tool functionality:** 
![reversal_final](https://user-images.githubusercontent.com/2844572/45289219-8d3e1780-b4e4-11e8-9296-3bb5a34d2407.gif)

**Correction tool functionality:** 
![correction_final](https://user-images.githubusercontent.com/2844572/45289226-916a3500-b4e4-11e8-8007-11cb32af15d0.gif)

**Comment by jniles** [comment]
This looks fantastic @sfount!  Great work!  I'll save my comments for when you believe it to be in a satisfactory state to be reviewed.
