### ISSUE TITLE
Sorting the Trial Balance is broken

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3330]
Looks like somewhere along the line sorting the Trial Balance got broken.  We need to make sure we've set `type: number` on all the columns.

See below for a reproduction of the issue:
![2018-11-10_12-02-52](https://user-images.githubusercontent.com/896472/48300590-c09b2380-e4e0-11e8-8fb1-92aac4b9ea75.gif)
_Fig 1: Sorting columns produces inconsistent results_

**Comment by Scholldier** [comment]
Hey @jniles 

A few of us St. Louisans were working on BHIMA last night, and we weren't able to reproduce this issue. However, we weren't able to post anything such that it would show up in Francs, currency wise, either. The code also looked like it was specifying the fields as number, too, in:

bhima-2.X/client/src/modules/journal/trial-balance/overview.js

Can you double check that this issue is really a problem, with the above in mind?

**Comment by jniles** [comment]
@Scholldier, thanks for follow up on this.  I'll have to take a second look.  We recently bumped the version of ui-grid to fix these kinds of bugs and it might have gotten cleaned up during that process.

I'll give it a whirl when I get into work and see if it's just me or if it is fixed or how better to attack the issue.

**Comment by jniles** [comment]
Can confirm that the problem still exists.  I'll take a swing at it and see if I can get it sorted (🥁 ).
