### ISSUE TITLE
Unify "Job Titles", "Professions", and "Functions"

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3354]
We seem to refer to the same thing in three different ways: "Job Title", "Profession" or "Function".  These three names are used interchangably in the tests, code, variable names, and translation keys.  In my mind, we are better served by picking one and renaming all references to being the same thing.  I would propose we use "professions" since that is recognizable and easier to manipulate than "Job Titles".

**Comment by diderikvw** [comment]
I will see what I can do as a first issue to pick up.

**Comment by diderikvw** [comment]
I am in the proces of carefully renaming stuff in the code, while seeing if the application still works and tests pass. It is quite challenging, as I need to go through pretty much the whole thing and are not yet very familiar with the architecture. And also because "function" happens to be a JS thingy as well. 
It looks like there is an entity in the database called "foncion", which could be French for function. Is the database schema indeed in French? And would I need to rename this as well?

**Comment by jniles** [comment]
Hi @diderikvw, apologies for the silence since your last comment.  I've been traveling with limited internet access and missed your first comment.

Thanks for working on this!  Yes, for legacy reasons, we have a mix of French/English in our database.  The "function" key is supposed to be the job title of profession of the person within the institution.  Here is the table:
https://github.com/IMA-WorldHealth/bhima/blob/68bb316ab8ac056f8a5c76d090fc12ef128fa85f/server/models/schema.sql#L639-L645

Let me know if you have any further questions!

**Comment by diderikvw** [comment]
Hi @jniles, thank you for the insights. Unfortunately I will not have time to continue working in this now and the foreseeable future. My work for Red Cross and other clients is taking up all my time at the moment.

**Comment by jniles** [comment]
This will be rolled up in the ongoing payroll refactor.
