### ISSUE TITLE
General Ledger looks broken without posted records

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3472]
If an enterprise hasn't posted any records for a fiscal year, the general ledger looks pretty blank.   Here it is below:
![nopostedrecordsmakesgeneralledgerlookbroken](https://user-images.githubusercontent.com/896472/49926050-face5b00-feba-11e8-9d7e-4afe536e17c7.jpg)
_Fig 1: General Ledger without posted records_

In this case, what we normally try to do is set an "empty state" message.  We should put something like "We cannot find any posted records for this fiscal year."

**Comment by joshuahedlund** [comment]
I think I've figured out how to do this one, can I take it?

**Comment by jniles** [comment]
Sounds good!  Let me know if you need any assistance!

**Comment by joshuahedlund** [comment]
So adding "empty-state" and "empty-state-message" to the bh-grid-loading-indicator tag (in general-ledger.html) works, but the problem is that the <select> tag to change the year is in the grid footer which gets hidden behind the empty message, so once you switch to an empty year you can't switch back.

In theory I don't see why the select has to be part of the div that gets refreshed... My first thought was to try moving the <select> out of it, but I quickly realized I'll need to figure out 1) how to fix the grid from taking up the same width on the page so you don't have to scroll down the page to see the select, and 2) how to populate the options there (maybe invoking Fiscal.read... from that startup function somewhere else...?)

My other thought would be to just try to limit the scope of what gets covered by the empty state message, but I don't know how customizable that is.

Or perhaps you know of a solution better than either... what do you think?

**Comment by jniles** [comment]
Hey @joshuahedlund, thanks for your work on this!  Things have been quite busy here.  I will be traveling back to the capital in the next couple of days and should be freer to help out on this.  Thanks!

**Comment by jniles** [comment]
@joshuahedlund, you have run into the same roadblock that I ran into a while ago and was too lazy to solve :).  Great work discovering this!

I agree with your approach to moving the select out of the General Ledger grid display.  That way, we don't tamper with the directive and potentially break other modules.

To resize the grid, you'll be in slightly new territory here.  The reason the grid currently takes up the full space is because we have a class [`.grid-full-height`](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/css/ui-grid.css#L44) that forces the calculation to be 100% of the view height, minus the pixel height of the top bar (which we once called a headercrumb and you'll see reference to that in the code comments).  It is kind of a hack.

Probably the easiest method would be to swap [`.grid-full-height`](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/css/ui-grid.css#L44) with [`.grid-full-height-with-filters`](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/css/ui-grid.css#L52) which gives it more space.  That should give you an extra row on the bottom of the page to put your `<select>`.

You are on the right track for populating the options.  The `startup()` method is called when the controller is invoked and it downloads the data.  The data is [bound to the controller with the name fiscalYears](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/modules/general-ledger/general-ledger.ctrl.js#L294).  So, from the HTML template, you will be able to use `GeneralLedgerCtrl.fiscalYears` to access the list of years.

From there, it is a straight forward `<select>`, powered by angular and `ngOptions`.  [We have an example of a fiscal year select here](https://github.com/IMA-WorldHealth/bhima/blob/master/client/src/modules/templates/bhFiscalYearSelect.tmpl.html#L9).

Thanks so much for your work on this!

**Comment by joshuahedlund** [comment]
Thanks so much, looks like this is working! A question on loose ends:

`gridFooterTemplate : '/modules/general-ledger/grid.footer.html',`
`    showGridFooter : false,`

I changed `showGridFooter` to false in the controller, but the template path is still defined and of course that file (which I stole the select from) still has those contents which are no longer being used. Should that be removed?

**Comment by jniles** [comment]
Yeah, if we are no longer using the grid footer, let's just remove it.  It will also give the General Ledger more space which we desperately need on such a large module.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima/pull/3522
