### ISSUE TITLE
Need to have a bulk patient group assignment feature

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3519]
I ran across a case where I wanted to label all patients in a search range as a particular patient group.  This was difficult as I needed to individually go through and change patient by patient their group status.  It would be helpful if we could have a bulk change patient group status, where any number of patients could be selected and their groups specified.  It would make that kind of operation much easier.

**Comment by kwilu** [comment]
Hello @jeremielodi, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!
