### ISSUE TITLE
Harmonize administration modules according 2.X style

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3689]
This issue is about to harmonize some modules of Administration folder in BHIMA according 2.x style : Grid and Modals

- [x] Supplier Management
- [x] Subsidies Management
- [ ] Patient Group Management
- [x] Localisation

**Comment by kwilu** [comment]
Hello @jeremielodi, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
I can confirm that this is done thanks to the hard work of @jeremielodi .
