### ISSUE TITLE
Add monthly, trimesterial, and annual reports automatic report sending

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3745]
We need a way to send reports automatically to the administrative team and others.  The basic components will be:
 1. A cron scheduler (like used in [sunfish](https://github.com/IMA-WorldHealth/sunfish/)) to determine when the reports will be sent.
 2. An interface to configure which reports are delivered automatically to which email addresses.
 3. An interface to monitor when the last emails were sent and their delivery status.
 
Prior art in BHIMA:
 1. Email reporting was implemented in https://github.com/IMA-WorldHealth/bhima/pull/2310
 2. Automatic delivery was started in https://github.com/IMA-WorldHealth/bhima/pull/1778 but not completed

**Comment by kwilu** [comment]
Hello @mbayopanda, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
I think this actually got fixed.  I'm closing, but @mbayopanda if you think it should be open, please re-open.
