### ISSUE TITLE
Do not render currency in MS Excel reports

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3764]
For most reports, if a report is rendered in MS Excel, we should not render the currency symbol.  This will allow users to easily export to MS Excel, and sum the values in the report.  Ideally, this would be an option during the "Save as MS Excel" option.

**Comment by kwilu** [comment]
Hello @jniles, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jeremielodi** [comment]
I don't think this issue is be easy to solve. The "Save as MS Excel"  option convert the "HTML template" into Ms excel file. If the user, after downloading the report, want to sum values in the report, he can just delete the symbol from excel and proceed to want he expect. That is quite easy.

**Comment by jniles** [comment]
It's more than this, though - the values themselves can be wrong.  For example, FC might be rendered as "10.000.00FC" which isn't a valid number.  So a user needs to be an expert Excel user to manipulate the report.

Can't we just turn the currency rendering off with an HTTP flag?  Like `?renderCurrency=0` which then tells the report not to use the currency renderer?
