### ISSUE TITLE
Feature creation of a Bhima data collection system

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#3863]
This issue proposes the creation of a complex system of data collection in BHIMA, this system will collect data, configure the survey form of a
dynamic and simple way,

The data to be collected can be of numeric type, text, choice list, text box, date, time, image (Photo), calculations with a particular synthax,

The use of this system will include the realization of three actions: development of a Data Collector Manager, lists of choices, as well as the elements of the survey form,
   Once these three conditions are met, data collection can begin.
  
   Some forms will have a link to patient management, it must also have a report with a mini search engine for data from surveys

**Comment by lomamech** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @lomamech, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 10 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 4 days.

If you've decided to work on something else, simply comment `@kwilu abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!
