### ISSUE TITLE
Implementation of a Configurable Analysis tool

### ISSUE THREAD

**Issue by lomamech** [third-culture-software/bhima#3891]
Implementing a set of support tools to assess the institution's ability to recover its revenues and to cover its costs and debts, the report resulting from this module will be an implementation computer report attached

![image](https://user-images.githubusercontent.com/8035588/65034901-d74fa980-d93f-11e9-9b87-d602b1f3ddc2.png)

**Comment by lomamech** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @lomamech, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 10 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 4 days.

If you've decided to work on something else, simply comment `@kwilu abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!
