### ISSUE TITLE
Stock requisition request from services

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#3912]
This issue is about to add a feature for services to do requisition requests for medicines from depots.

---------------------

Stock requisitions require four different elements:

1. La désignation des médicaments (Inventory items)
2. Le conditionnement (inventory type - size of pills etc)
3. La quantité (# of each inventory)
4. La possibilité de préciser à qui vous adressez la réquisition (depot to request from)

**Comment by kwilu** [comment]
Hello @jniles, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 10 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 4 days.

If you've decided to work on something else, simply comment `@kwilu abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima/pull/3991.
