### ISSUE TITLE
Registre d'acceptation

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3968]
We have received this feature request:

> J'ai pensé proposer l’implémentation d'un registre dit d'acceptation, dans le module stock. En effet, le souci étant de rester positivement plus proche des pratiques d'usage dans le monde professionnel des hôpitaux, ce registre est un des documents demandés lors des missions de supervision. Il va faire référence au document généré quand on soumet une entrée en stock en provenance de l’extérieur (voir image en PJ). Seulement que la présentation du registre sera exactement comme celle du registre des achats; quand on clique sur voir le document, ça nous ramène au document en image ci haut mentionné.
Merci pour votre attention et franche collaboration.

Basically, we need to show the same level of detail that we do for a purchase order registry, but for all stock entries.  It might be a new module, or an enhancement to the existing stock entry registry.

**Comment by kwilu** [comment]
Hello @mbayopanda, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!
