### ISSUE TITLE
Add report for all changes to inventory items, not just for a single inventory item

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#3975]
After demonstrating our "Inventory History" feature to the Medical Director of Vanga Hospital, he requested we provide the ability to view a global report of all items that have changed, not the individual history item by item.  This would allow him to view any changes at any time.

**Comment by kwilu** [comment]
Hello @jeremielodi, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 10 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 4 days.

If you've decided to work on something else, simply comment `@kwilu abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!
