### ISSUE TITLE
Fix Debts Report

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#4014]
The Client debts report shows : 
- Double the amount found in the account report
- Display details always in $

![image](https://user-images.githubusercontent.com/896472/69338231-01d12200-0c63-11ea-8428-d8c1c2a0d953.png)

**Comment by jniles** [comment]
I'll grab this one

**Comment by kwilu** [comment]
Hello @jniles, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
@kwilu claim

**Comment by jniles** [comment]
So, I'm not sure if this report makes a lot of sense.  A debt shouldn't be related to a date range - it should be for all time, I think?  I may go ahead and change this to consider debts for all time rather than for a particular time period.
