### ISSUE TITLE
Rewrite cashbox and depot assignment modals to use checkboxes

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4044]
The cashbox and depot assignment modals in the users and permissions management are currently cumbersome to use.  The assignments disappear because the z-index isn't set correctly, and it is difficult to see all values together.  For example:

![image](https://user-images.githubusercontent.com/896472/70711914-ec3f9d00-1ce2-11ea-9e59-07c3167380e7.png)

For the most part, we won't have a lot of cashboxes or depots.  Instead, we should allow the user to check them via a list of checkboxes, like we do for permissions:

![image](https://user-images.githubusercontent.com/896472/70711949-08433e80-1ce3-11ea-943c-0c98c8d51f88.png)

This will make the experience much more user-friendly.

**Comment by jniles** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @jniles, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
@kwilu claim
