### ISSUE TITLE
Rewrite Stock Adjustments to take in a quantity and make the correct adjustments

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4076]
Our Stock Adjustments requires the user to:
 1. Pick augmentation or reduction
 2. List all articles that are increased or decreased by the _amount_ of the increase or decrease

This is not user friendly.  A better way, proposed by our partners in Vanga, would be to record the _amount_ of each lot when you do an inventory, and let the system figure out whether it increased or decreased and generate the final transaction.  We should implement this method to save time from our users.

Here is an example to gain inspiration from:
![Stock Inventory Adjustment](https://user-images.githubusercontent.com/896472/78895023-048fb080-7a66-11ea-8b32-633f7f4f4854.png)

**Comment by kwilu** [comment]
Hello @mbayopanda, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima/pull/4369
