### ISSUE TITLE
Download payroll information in Excel format

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4089]
As pointed out by @lomamech, it would be nice to have the bulletin de paie and other payroll documents available for download as MS Excel.  This would allow an administrator to rapidly do calculations by exporting the data from BHIMA.

See https://github.com/IMA-WorldHealth/bhima/pull/4077 for further discussion.

**Comment by lomamech** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @lomamech, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 10 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 4 days.

If you've decided to work on something else, simply comment `@kwilu abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!
