### ISSUE TITLE
Is "Global Quantity" useful in stock entry?

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4092]
In the section for stock entry, we have a "Global Quantity" field.  How useful is this field in practice?  theoretically, we hope it will avoid import errors by forcing users to declare the number of items in the lot, but I wonder if this actually plays out in the field.  It is certainly annoying when trying to test things:

![image](https://user-images.githubusercontent.com/896472/72414107-bffbbe00-3771-11ea-8630-34ef516600c9.png)

**Comment by jniles** [comment]
Okay, I have a follow-up question.  I can see this being useful for purchase orders, for example.  But should it be editable during a purchase entry?

**Comment by jmcameron** [comment]
> Okay, I have a follow-up question. I can see this being useful for purchase orders, for example. But should it be editable during a purchase entry?

1. Not sure this field makes sense unless we are entering stock from a purchase order.   Consider donations or integrations:  Where should the "global quantity" come from?   The quantity is what it is and I don't think there is any way to know that in advance.   

2. During entry from purchases, what happens if we receive more items than ordered in the PO?

**Comment by jmcameron** [comment]
Superseded by https://github.com/IMA-WorldHealth/bhima/issues/6645
