### ISSUE TITLE
Stock Value report crashes server with too much data

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4116]
As reported by our friends in Vanga, the stock value report appears to crash the server for the "pharmacie usage", the most trafficked depot in the institution.  On my local machine, MySQL pins the CPU at 100% and eventually the server dies.

It looks like the entire report is in a [stored procedure,](https://github.com/IMA-WorldHealth/bhima/blob/master/server/models/procedures/stock.sql#L275) which is good, but uses a for loop instead of JOINs/GROUP BYs, which is bad.  It appears this report is unusable until rewritten.

**Comment by kwilu** [comment]
Hello @mbayopanda, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by lomamech** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Hello @lomamech, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by lomamech** [comment]
@kwilu claim
