### ISSUE TITLE
Add a start date limit to fiche de stocks report

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4401]
Here is the current presentation of the fiche de stocks:
![image](https://user-images.githubusercontent.com/896472/80700697-1220df00-8ad6-11ea-968c-99eccd00a56e.png)

It offers only an end date. The problem is that when you have a busy medicine (one with lots of entries and exits) the report gets really difficult to read.  Here is an example: 
![KmjE7r65ZH](https://user-images.githubusercontent.com/896472/80701178-e8b48300-8ad6-11ea-9e7c-f5647a059408.gif)

You can see how, as time goes on, this will get really difficult to manage.  I propose that we add a start date and end date so that we can produce more valuable reports.

**Comment by kwilu** [comment]
Hello @jeremielodi, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!
