### ISSUE TITLE
Add link to account statement on account dropdown in Account Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4483]
I was curious if some blocked accounts had remaining balances.  I'm lazy and don't want to look them up in the Simple Account statement report.  Let's put a link in the Account Management dropdown that takes me to the Simple Account Statement report and populates it with the account number selected.

![image](https://user-images.githubusercontent.com/896472/81499486-ef57ad00-92c3-11ea-8486-ee9a17ac3df8.png)

**Comment by kwilu** [comment]
Hello @jniles, @jeremielodi, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
@kwilu claim
