### ISSUE TITLE
HTTP result codes different when running on MySQL 8 vs. 5.7

### ISSUE THREAD

**Issue by individual-it** [third-culture-software/bhima#4501]
when sending a string to the API instead of a int in some cases the API responses with HTTP 404 on MySQL 5.7 and HTTP 400 on MySQL 8

see this discussion for details: https://github.com/IMA-WorldHealth/bhima/pull/4473#issuecomment-627096996

**Comment by jniles** [comment]
Copying the discussion from: https://github.com/IMA-WorldHealth/bhima/pull/4473#issuecomment-627096996 for brevity:

----

The question is now how do you want the software to react when an invalid data-type is send to the API endpoint. For some requests there are checks like
```js
if (!rows.length) {
        throw new NotFound(`
          Could not find a cash box account currency with id ${req.params.currencyId}.
        `);
      }
```
So if the DB returns no rows the client received a 404, MySQL 5.7 returns 0 rows when getting n invalid data-type but MySQL 8 throws an exception already when executing the query and the client receives a 400 Error.

We could:
  1. adjust the tests to expect different results when running on different DB - would be strange to have the API react differently depending on the database
  2. check the data-type before running the query and throw BadRequest if its wrong - that would emulate the MySQL 8 behaviour in MySQL 5.7
  3. catch the exception of MySQL 8 and re-throw NotFound - that would keep the API behaviour as it is, currently

**Comment by jniles** [comment]
My personal preference of these is the third option - it would be the easiest to handle, I believe because we ultimately re-throw a lot of the DB errors in [interceptors.js](https://github.com/IMA-WorldHealth/bhima/blob/master/server/config/interceptors.js).  We would just need to discern somehow if we were sitting on MySQL 8 and change the error slightly.

Potentially I'm oversimplifying, but that would be the tack to take until we have more information.

**Comment by individual-it** [comment]
@jeremielodi a POC in #4511 
please have a look at that approach.
Before I do more refactoring I would like to have your approval for the way forward

**Comment by individual-it** [comment]
PR in #4511
