### ISSUE TITLE
Set up end-to-end tests on BrowserStack

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4541]
A while ago, we tried to get end to end tests running on SauceLabs (https://github.com/IMA-WorldHealth/bhima/issues/25).  Unfortunately, they block Congo's IP addresses, so this is unworkable.

Now that we have a ton of tests across multiple environments (and lots of flakey-ness it seems), we should really investigate a tool like SauceLabs to run out tests.  I'm investigating BrowserStack to see if it will give us greater visibility into our tests and better predictability in our testing.

**Comment by kwilu** [comment]
Hello @jniles, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!

**Comment by jniles** [comment]
Still working on it.

**Comment by jniles** [comment]
Closing this as irrelevant now that Travis has killed the free tier.
