### ISSUE TITLE
Link to User Management registry from Role Management

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4598]
It would be nice if we could link to the users who have a particular role from the Role Management registry.  Like this:

![image](https://user-images.githubusercontent.com/896472/84282051-2faf8280-ab31-11ea-892d-6305060ef08b.png)

Basically, we would add an `a href` that links to the User Management registry and filters the users on those that have this role.

**Comment by kwilu** [comment]
Hello @jniles, you have been unassigned from this issue because you have not updated this issue or any referenced pull requests for over 14 days.

You can reclaim this issue or claim any other issue by commenting `@kwilu claim` on that issue.

Thanks for your contributions, and hope to see you again soon!
