### ISSUE TITLE
Remove lib/tree in favor of @ima-worldhealth/tree

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4634]
A long time ago, we broke out the `lib/tree` library into an NPM module that could be upgraded/tested separately.  But we never completed the work of migrating to it fully.  We should remove the `lib/tree` library and the unit tests for it, and instead use the `@ima-worldhealth/tree` library.  Whoever does this should run some tests and make sure they behave the same.

**Comment by jniles** [comment]
Just a note - I've asked @jmcameron to tackle this.

**Comment by jmcameron** [comment]
@kwilu claim

**Comment by kwilu** [comment]
Welcome to BHIMA, @jmcameron! We just sent you an invite to collaborate on this repository at https://github.com/IMA-WorldHealth/bhima/invitations. Please accept this invite in order to claim this issue and begin a fun, rewarding experience contributing to BHIMA!

As you work on this issue, you'll also want to refer to the [BHIMA code contribution resources](https://github.com/IMA-WorldHealth/bhima/wiki), as well as the rest of the developer documentation on that site.

See you on the other side (that is, the pull request side)!
