### ISSUE TITLE
Patient Documents Review

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#475]
This issue tracks re-factors/ improvements to the Patient Documents feature, this will track until the feature is production ready 2.x.0. 
- [ ] Update feature to use the latest 2.x sub module structure _\- note this is not yet decided, this should be updated following the patient check in feature proof of concept_

**Comment by sfount** [comment]
I suggest that we make the following refinements to bring the feature inline with the module and other units: 
- Constrain the feature to a panel for now, removing the individual page 
- Inline all of the full page features (adding documents etc.) into the panel header

Design questions:
Do we need to preview the upload in the modal? It could be a very small modal that just deals with uploading the image and displaying meta data - the file would then be displayed in list form.

**Comment by jniles** [comment]
A few other improvements:
1. The buttons for delete, download, and preview should always be visible.
2. The file size should be shown next to the file name, so that the user knows how large a download is.
3. Should there be a way to clean up records in the database if the file doesn't exist locally?  How about deleting files clearing the files on disk?

**Comment by sfount** [comment]
After reviewing patient image uploads I've noticed that uploads so far do not handle the ng-upload directives errors - if an invalid file is passed to the directive nothing will be displayed (in the case of patient documents this means the file does not match any of the specified types). 

This should be handled before feature completion.
