### ISSUE TITLE
Feature - Account Locking 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#490]
In 1.x Account locking was a simple as ticking a check box that directly set a configuration option in the database from 0 to 1. 

Whilst this still may be a good way to model an accounts locked status (flag on a database table) this feature should be carefully implemented in 2.x. 

**Initial states that should be considered**
- Tests on any modules that import/ write/ use accounts - additional test case for accounts being locked 
- Server side report querries on Locked Accounts
- Implications on locking accounts currently in the posting journal 
- Implications on locking accounts that have not been used

I suggest that the feature is implemented as an action the user can take instead of a flag that can be set; i.e 'Submit Lock Account' vs. 'Account Locked -> True'

This design thread is to discuss the implications of Account locking on the accounting/ technical implementation. If agreed upon the feature will be build on top of https://github.com/IMA-WorldHealth/bhima-2.X/issues/489.

**Comment by jniles** [comment]
In my view, account locking will be especially important for organisations that are migrating their charts of accounts.  For example, from PCGC to OHADA.

Locking an account should create the following behaviors:
 1. Accounts that are locked cannot be posted to the GL.  I'm in favor of allowing them to be written to so that we don't lose data.  If the transaction really happened, they can always change the account to a correct account later in the Journal.
 2. Locking an account should require confirmation, but no other checks are necessary.  It would be super cool if we could say "This account is used in XYZ place", but we don't have the infrastructure to support this yet.
 3. You cannot lock a title account.
 4. Locked accounts are not available for selection anywhere in the application - not in the cashbox selection, complex vouchers, debtor group creation pages, billing services, inventory, nowhere.
 5. Locked accounts could optionally be printed in reports.  However, this must be a feature that is enabled, rather than on by default.

@IMA-WorldHealth/bhima-core what you do think?

**Comment by jniles** [comment]
The current IMCK database has 2,400+ accounts, yet they have only used 197 (~6.8%) of those in 2018. In my view, we should add support for account locking before doing the IMCK upgrade.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/2810
