### ISSUE TITLE
Migration for non-test databases is broken

### ISSUE THREAD

**Issue by jmcameron** [third-culture-software/bhima#5021]
We seem to have a problem with the typical migration procedure for the non-test databases.  I've confirmed this for both IMCK and Vanga. 

The following procedure fails in the last step.  These use the "fetch" and "build" scripts provided to me some time ago.  I'll attach the (slightly updated) versions I use here.  I modified the fetch script to put the files in specific location on my system.

Here is the procedure I used:
  - **DATABASE=imck bhima-fetch-latest-backup.sh**
     - runs fine with no prompts
  - **DATABASE=imck bhima-fetch-latest-backup.sh**
     - enter mysql root password twice, runs slow but without problems
  - Edit .env to change:  DB_NAME='imck'
  - **yarn migrate**
      - Runs fine, produces migration-imck.sql
  - **mysql -u bhima -p --database=imck < migration-imck.sql**
     - type in 'bhima' password
     - Produces this error:
          _ERROR 1054 (42S22) at line 222: Unknown column 'project_id' in 'NEW'_
     - Offending SQL:
          _CREATE TRIGGER stock_requisition_reference BEFORE INSERT ON stock_requisition_
          _FOR EACH ROW_
          _SET NEW.reference = (SELECT IF(NEW.reference, NEW.reference, IFNULL(MAX(stock_requisition.reference) + 1, 1)) FROM stock_requisition  WHERE stock_requisition.project_id = new.project_id);$$_

Note that I do not see this SQL in server/migrate/next/migrate.sql.  This seems to be something produced by the 'yarn migrate' script.

I see the same error when I follow this procedure for the Vanga database.

[bhima-build-backup.sh.txt](https://github.com/IMA-WorldHealth/bhima/files/5374184/bhima-build-backup.sh.txt)
[bhima-fetch-latest-backup.sh.txt](https://github.com/IMA-WorldHealth/bhima/files/5374185/bhima-fetch-latest-backup.sh.txt)

**Comment by jniles** [comment]
@kwilu claim

**Comment by jniles** [comment]
Confirmed while testing https://github.com/IMA-WorldHealth/bhima/pull/5022.  Thanks for reporting @jmcameron !

The problem was introduced in this trigger:
https://github.com/lomamech/bhima-2.X/blob/c2af45e0bad153599e8cb1e59364ba2b14f05d42/server/models/triggers.sql#L122-L126

```sql
CREATE TRIGGER stock_requisition_document_map AFTER INSERT ON stock_requisition
FOR EACH ROW BEGIN
  INSERT INTO document_map
    SELECT new.uuid, CONCAT_WS('.', 'SREQ', project.abbr, new.reference) FROM project WHERE project.id = new.project_id ON DUPLICATE KEY UPDATE text=text;
END$$
```

This is actually a chicken and egg problem.  MySQL rightly doesn't allow you to create a trigger using a column that doesn't exist.  The column is defined later in the migration script.  The fix in this case, is that want to run the updates to the schema first, _then_ the procedures/triggers/etc.  It's unclear to me is that is what we always want to do though.  I can imagine using a new procedure/trigger when writing migration code (and hence, the reverse problem). 

@jmcameron What are your thoughts on this?  This easy fix would be to simply `cat` the migration script `next.sql` to the beginning of the migration process.  I'm not sure if that is the best solution though.

**Comment by jmcameron** [comment]
It seems to me that that trigger should have been added in migrate.sql until the next release.  Which would imply that the 'yarn build:db' should handle migration itself.  Not sure that is robust.    

I think the underlying problem is that we are treating loading the SQL differently for bhima_test (all pre-defined) and the other production databases (basics from actual data + migration procedure).  

Perhaps we should consider handling all the databases the same way and have 'yarn build:db' handle migration for Bhima_test.  That way the developer who implements the changes has a good chance to catch problems like this.

It also seems like a release was done without adequately testing with production databases.

**Comment by jniles** [comment]
The `next/migrate.sql` hasn't been released yet, so no worries about the testing on production databases - it's all a part of the bleeding edge.  When we actually go to publish that file as a release, we test it extensively against the production databases.

I'm not sure I'm understanding your idea about migrating the in the build:db step.  Does that mean if we have a plain schema, then we introduce a feature that includes a table `x`, then two months later, we drop that feature since it wasn't a good idea, our migration script will continue to build table `x` then drop table `x`, each build:db despite it no longer being relevant?

I do agree that `migrate.sql` not being able to be run is a problem.  I think we had a few broken merges and some ordering issues in creating it, but we did have some rather large merges all hitting at the same time, so it isn't too concerning.  Just a headache if you want to try and update one of our production databases to the unreleased/bleeding edge since those scripts don't work currently (pull requests welcome!).

**Comment by jmcameron** [comment]
So we only install release versions of Bhima on production environments?
Which means that the problem comes in when we want to test with production databases -- that is the only time that 'yarn migrate' used?

**Comment by jniles** [comment]
That is correct - all install should be running release versions.  It doesn't always happen that way, but we try to make it work that way.

`yarn migrate` is used to prepare a release upgrade.  Basically, when we want to release another version, we first use `yarn migrate` to prep the sql code we'll need to run on the production server.  We then test it locally (build production on local machine, run migration, use the app), then transfer the migration script over to the production environment and run it there.

Why?  Because we've had issues before where we forgot to include something in the migration code and that broke production.  So, as a safeguard, we rebuild all stored procedures, triggers, functions, etc, from source.   Then we do data definition updates and migrate data. 

The issue here was multiple - our trigger used a column before it was defined in the data definition update code.  Beyond that, we also had issues after even resolving that with our stock_settings table migration.
