### ISSUE TITLE
Add a banner to the BHIMA login page

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5031]
As we will be deploying a BHIMA server nationwide, we will want to redirect users to helpdesks if they forget their password.  Here is how DHIS2 solves this problem:

![image](https://user-images.githubusercontent.com/896472/96449114-4915b900-120c-11eb-939b-050fd14701ae.png)

This is a custom "banner" that you can add to the home page.  I propose we do the same thing in BHIMA.  This would be a `textarea`, part of the enterprise information.  It will be displayed on every login page.

If the `banner` section is empty in the enterprise information, don't show anything.  The behavior will be identical to the current behavior.

**Comment by jniles** [comment]
@jmcameron this will also be a really useful feature to work on if you run out of things to do. 👍

**Comment by jmcameron** [comment]
I've gotten this partly done but I'm running into a snag:  Not sure how to get the enterprise info without logging in!  If I use the EnterpriseService and try to do its read() function to get the enterprise info, it does an http request which requires us to be logged in.  But that is a bit of problem since we are trying to access that info BEFORE logging in! 
Suggestions?

**Comment by jmcameron** [comment]
Also, if I cache the helpdesk info after the login, that works after that, but when starting Bhima fresh (cleaned cache), the helpdesk info will not be available when the user needs it most!   Perhaps we need to make the /enterprises path or some variant accessible without logging in.   Or even just a special path to get just the helpdesk info?

**Comment by jniles** [comment]
We actually already have this issue for projects.  Our work around is to just select the first enterprise in the database.  We've never had multiple enterprises hosted on a single BHIMA instance (and likely never will).  It's "good enough" for now.

**Comment by jmcameron** [comment]
> We actually already have this issue for projects. Our work around is to just select the first enterprise in the database. We've never had multiple enterprises hosted on a single BHIMA instance (and likely never will). It's "good enough" for now.

That helps but does not address the real problem.  Where do we get the helpdesk info string from?   We are not logged in and getting that helpdesk info string requires a DB query (even assuming we know which enterprise to use).   Since the /enterprise REST call requires logging in, we have reached chicken-and-egg problem.   My proposal would be to add a new REST call (eg /helpdesk_info) that would NOT require login so it can be done even when logged off.  If that seems like a reasonable approach let me know.  If there is some other work-around I was not able to find it.

**Comment by jmcameron** [comment]
I've worked this out and will do a PR for it in a few minutes.
