### ISSUE TITLE
Do not present inventory for selection in stock exit if no viable lots available

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5040]
If there are no viable lots for the inventory, we should not show it as an option to distribute stock to.  This can happen for a couple reasons:
  1. There were lots, but they are being used in a other lines above.
  2. There are lots, but they are expired.
  3. ?

By hiding these lots, we have a weird user interface.  Here I am reproducing it:

![KcyRk3w4HS](https://user-images.githubusercontent.com/896472/96863754-4068f100-145f-11eb-9cb4-5dfcf47eb13f.gif)

Instead, we should remove the inventory from the pool of options, rather than letting the user select it and then finding nothing.

**Comment by jmcameron** [comment]
I think I understand the issue but when I watched the little gif clip, I noticed that the Oxytocine was not visible the second time even though you had specified 0 quantity above.  My question is: If you did include a line with a quantity less than the total available in that lot, should you then be able to add it a second time (since there is still stock left in the lot), or should you just never allow the same lot to be specified twice in the list.   As you noticed, the current UI does not do either approach cleanly.
