### ISSUE TITLE
Standardize the way we name reports

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5110]
In working on https://github.com/IMA-WorldHealth/bhima/issues/5108, I realized that we use three forms of naming our reports:
  1. `camelCase`
  2. `snake-case`
  3. `underscore_case`.

This is kinda confusing in the long run and it makes me confused about how I should name my reports.  Let's pick one and stick to it.  I prefer either `snake-case` or `underscore_case` since it isn't case sensitive, but I don't really care which one we use.

My initial vote goes to `snake-case` because it looks like our components.  @mbayopanda @lomamech @jmcameron what do you think?

**Comment by jmcameron** [comment]
For reference, I looked through server/config/routes.js and here are some stats:

- It looks like there are 77 GET urls for reports
- 25 use underscore_case
- 2 use snake-case
- 10 use camelCase
- The rest are just single words and none of these apply

If we have any thought of going back to regularize the existing report names, we should choose underscore_case since it would involve less work.    Either underscore_case or snake-case are fine with me.

**Comment by jniles** [comment]
The logic is sound.  Thanks for the research!  I am changing my vote now to `underscore_case` based on the fact that we won't need to change as many routes. 😄

**Comment by jniles** [comment]
@jmcameron want to grab this one?
