### ISSUE TITLE
Stock Adjustment Receipt

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5428]
The stock adjustment receipt doesn't have information about the adjustment, it contains just the inventories after the adjustment

![image](https://user-images.githubusercontent.com/5445251/109117351-2a877780-7742-11eb-8276-425c105b6f55.png)

The proposal is to have these pieces of information in the adjustment receipt : 
- Depot
- Date
- Description
- Inventories adjusted
- Lots adjusted
- Previous quantities
- New quantities
- The quantity difference
- Information about the user

**Comment by jniles** [comment]
I like this proposal.  It would be a much better user experience that what actually exists.

It seems to me the reason we didn't implement this in the first place is because the adjustment takes place in two separate transactions - on that makes the stock go from `old value` -> `0`, then from `0` -> `new value`.  We might need to change the logic so that we just go from `old value` -> `new value` instead to be able to show it all on one receipt.

**Comment by jniles** [comment]
@mbayopanda did this get fixed?

**Comment by mbayopanda** [comment]
@jniles yes it has been already fixed
