### ISSUE TITLE
Should we consider "before depot had stock" as stock out?

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5482]
Here is an interesting case from Bandunduville:

![image](https://user-images.githubusercontent.com/896472/110307515-440ca700-7fff-11eb-94ee-3ecb3666b65b.png)

You'll notice that the period of CMM is 6 months, yet they were only installed this year (2021).  The first stock movement, presumably an entry, was made in February 2021.  That means, we are treating about 4ish months where the depot wasn't operation as days with stock.

Interestingly, if I move the number of months down to 3 months for the CMM calculation:

![image](https://user-images.githubusercontent.com/896472/110307915-c4cba300-7fff-11eb-9048-592213cd1eb2.png)

This doubles the CMM by halfing the period.  This doesn't seem right to me.

Should we consider "days before the depot had stock" as "days of stock out"?  This would fix the above issue.  But it might also freak users out because they were not technically in stock out.  Or should we modify the CMM algorithm by MSH to account for this?  Or should we just tell users that their CMM might not be right because the period is too large?

**Comment by jmcameron** [comment]
What happens if you make the "Days of stock-out" be 3*30.5 (3 months)?
    MSH:    515 / (6 - (3\*30.5/30.5)) = 171.67
So that is equivalent to using CMM period of 3 months.

I think this may be the right answer, and that the result of the first calculation with 0 days of stock out (85.83) is incorrect because it's estimate of CMM is artificially low.

So it seems to me that we need to treat the days of the CMM period before initial stock is received as "stock out".

**Comment by jniles** [comment]
That makes the most sense to me as well.  Thanks @jmcameron !

**Comment by jniles** [comment]
Uh, it looks like this was actually a bug.  🤦  I'm going to fix it.
