### ISSUE TITLE
Currency function crash after exporting document in Excel

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#5798]
This issue is about the fact that the currency function in handlebars crashes when we export a generated report in Excel format.

How to reproduce : 
1. Go to stock -> reports -> stock value report
2. Generate a report
3. Save the report as Excel
4. Download the Excel file

You will notice that the currency doesn't work 

![image](https://user-images.githubusercontent.com/5445251/126483752-c211d38d-fbf2-46e0-b584-12315444d527.png)

**Comment by jniles** [comment]
This might be on purpose.

https://github.com/IMA-WorldHealth/bhima/blob/master/server/lib/renderers/xls.js#L19

We skip currency rendering in the HTML export before making it into an XLS file.  This was a request from Vanga since trying to remove all the FCs to allow Excel to SUM() the values was hard.  Can you verify that if you switch the `options.skipCurrencyRendering` flag off, it all works?
