### ISSUE TITLE
Create allocation keys based real-world measures, not percentages

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#5879]
Currently, BHIMA stores allocation keys based on a percentage that is calculated by the accountant.  Here is how we model them right now:

https://github.com/IMA-WorldHealth/bhima/blob/233f9353f56a3d99bfa3ee2734bed47f8c26678d/server/models/schema.sql#L2242-L2255

However, storing based on a percentage isn't really helpful - these percentages are derived from something, such as number of cases, number of square foot, etc.  You can imagine a layout like this:

Centres | Nombre Metres Carre | Frequentation | Heures de travaille
-- | -- | -- | --
Chirurgie | 250 | 1500 | 1600
Maternite | 300 | 2000 | 800
Maintenance | 10 | 0 | 300
Pediatrie | 250 | 1500 | 700
Electricte | 0 | 0 | 0
Med. Interne | 150 | 1700 | 1200
Pav. Med | 500 | 250 | 500
Tax | 0 | 0 | 0

In this layout, we can calculate the percentage contribution of each center as it relates to each column.  This allows us to change the number of square footages of Maternite, for example, without having to recompute _all_ percentages.  It also allows users to see exactly what kind of index is being used to calculate the cost allocations.

**Comment by jniles** [comment]
Note that these allocations keys will come in three forms:

1. Static keys (e.g. square footage)
2. Dynamic keys that BHIMA can look up (.e.g number of employees, number of cases, number of patients)
3. Dynamic keys that must be set (e.g. number of kilograms of laundry)

The dynamic keys are discussed in more detail in https://github.com/IMA-WorldHealth/bhima/issues/5875.

**Comment by jmcameron** [comment]
**A word on the allocation bases:**  These need to be flexible and able to be defined by the site administrator.  I could see that they operate similarly to tags, but would have some type information and a value associated with them.  One of the nice things about the step-down allocation algorithm currently being implemented, is that it uses a user-defined basis label so it is very flexible.  For instance it is not hard to imagine a situation where an auxiliary center provides services that can be quantified in two different ways.  For instance the Laundry service could be done by "kg of laundry processed for each service" or "number of pieces processed for each service".   We will need the flexibility to create these basis items on the fly since we cannot predict all the possible types of bases.

(Moved here from Issue https://github.com/IMA-WorldHealth/bhima/issues/5888.)

**Comment by jmcameron** [comment]
> Note that these allocations keys will come in three forms:
> 
>     1. Static keys (e.g. square footage)
> 
>     2. Dynamic keys that BHIMA can look up (.e.g number of employees, number of cases, number of patients)
> 
>     3. Dynamic keys that must be set (e.g. number of kilograms of laundry)

How are 'static' keys (1) different from 'Dynamic keys that must be set' (3).  Aren't these the same thing?

**Comment by jniles** [comment]
@jmcameron good question.  I'm thinking there may be a UX optimisation where you never change square footage, so we don't need to set it to run the analysis, but KG of laundry must be set each time before you run the analysis.  If this is burdensome to treat these different, yes, you are right, they are effectively the same thing.

**Comment by jmcameron** [comment]
> @jmcameron good question. I'm thinking there may be a UX optimisation where you never change square footage, so we don't need to set it to run the analysis, but KG of laundry must be set each time before you run the analysis. If this is burdensome to treat these different, yes, you are right, they are effectively the same thing.

I think we should treat them the same.  If we need to change them we will know.  Even "dynamic" (3) ones that change from month to month will not always need changing.    And the ones that are "static" will need changing from time to time too.

**Comment by jniles** [comment]
Fine by me

**Comment by jmcameron** [comment]
Here is what I propose for the allocation keys (pseudo-SQL):
```
   TABLE `allocation_basis` ( 
      uuid
      cost_center_id
      name : string
      constant : boolean
      value : float  (default = 0)
      function : string
    );
```

NOTE: We will have to decide whether this replaces the current distribution_key or is a parallel entity.

If 'constant' is true, the user will be able to edit its 'value'.  If it is false, 'function' is the name of the function to be called (possibly passing the cost_center_id as an argument).   The list of allowable function names would be encoded in an array in bhConstants (or similar constant on the server side).   

We would need to provide a mechanism (perhaps a function of the cost center API), that would take the string name for the function and invoke it and return the results.   The function call should produce a floating point number.

The data for ALL the cost centers provided for a step-down analysis must include the 'name' of each allocation basis names that are called for for all the desired cost center allocations.  

As was done in PR https://github.com/IMA-WorldHealth/bhima/pull/5894, the data for each cost center will include an 'allocation' definition that will look like:

   allocation : { method : 'proportion', field : <allocationName> }

The algorithm <allocationName> values here must be ones that correspond to one of the 'name' fields in the 'allocation_basis' fields.

When the cost center step-down controller prepares data for the step-down analysis, it will use the 'allocation' field of each cost center to verify that the data for every cost center contains that data.

Note that the (SQL table) for cost centers will need to add columns for the 'allocationMethod' and 'allocationField'.  These may be edited by the user before cost center breakdown analysis is done to control how the allocations are done.

Since the names of the allocation_basis can vary from situation to situation, they cannot be hard-coded in advance.  Therefore, the table proposed at the top of this comment should be used.  The form for editing the data for a cost center will need to include a section that lists the values of allocation_keys defined for that cost center and supports editing their values or adding new allocation_keys.  This form should also have a clearly visible reminder of the allocation_keys that are currently needed (based on the allocation.field values currently selected in the system) and have a button for adding missing allocation_basis entries easily (with default values).

**Comment by jniles** [comment]
@jmcameron this looks pretty good.

As discussed on Skype, I think the `function` part isn't necessary - we will either have the value stored in this table, or we will use an external API to get the values and either (1) use them as is or (2) write them to this table, then use them to compute the step down.

Otherwise, this looks good to me!

**Comment by mbayopanda** [comment]
> 
> 
> Here is what I propose for the allocation keys (pseudo-SQL):
> 
> ```
>    TABLE `allocation_basis` ( 
>       uuid
>       cost_center_id
>       name : string
>       constant : boolean
>       value : float  (default = 0)
>       function : string
>     );
> ```
> 
> NOTE: We will have to decide whether this replaces the current distribution_key or is a parallel entity.
> 
> If 'constant' is true, the user will be able to edit its 'value'. If it is false, 'function' is the name of the function to be called (possibly passing the cost_center_id as an argument). The list of allowable function names would be encoded in an array in bhConstants (or similar constant on the server side).
> 
> We would need to provide a mechanism (perhaps a function of the cost center API), that would take the string name for the function and invoke it and return the results. The function call should produce a floating point number.
> 
> The data for ALL the cost centers provided for a step-down analysis must include the 'name' of each allocation basis names that are called for for all the desired cost center allocations.
> 
> As was done in PR #5894, the data for each cost center will include an 'allocation' definition that will look like:
> 
> allocation : { method : 'proportion', field : }
> 
> The algorithm values here must be ones that correspond to one of the 'name' fields in the 'allocation_basis' fields.
> 
> When the cost center step-down controller prepares data for the step-down analysis, it will use the 'allocation' field of each cost center to verify that the data for every cost center contains that data.
> 
> Note that the (SQL table) for cost centers will need to add columns for the 'allocationMethod' and 'allocationField'. These may be edited by the user before cost center breakdown analysis is done to control how the allocations are done.
> 
> Since the names of the allocation_basis can vary from situation to situation, they cannot be hard-coded in advance. Therefore, the table proposed at the top of this comment should be used. The form for editing the data for a cost center will need to include a section that lists the values of allocation_keys defined for that cost center and supports editing their values or adding new allocation_keys. This form should also have a clearly visible reminder of the allocation_keys that are currently needed (based on the allocation.field values currently selected in the system) and have a button for adding missing allocation_basis entries easily (with default values).

It seems clear, I would like just to know examples of function that we can use or set in the `function` column. 

Also, I am wondering if we can split this table into two table `allocation_basis` and `allocation_basis_value`

```sql
CREATE TABLE `allocation_basis` (
  `id` mediumINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NOT NULL,
  `constant` TINYINT(1),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `allocation_basis_value` (
  `allocation_basis_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `cost_center_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `value` decimal(19,4) UNSIGNED DEFAULT NULL,
  `function` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;
```

**Comment by jmcameron** [comment]
Also, based my discussions with @jniles  and our earlier discussions about the step-down algorithm, the only two values of '**allocationMethod**' that will be initially supported are:
- **proportion** => meaning the allocation ratios will be computed based on the proportions of each allocation field for all remaining centers at that step of the step-down procedure.  This would be the most common usage.
- **flat** => meaning the allocation ratios will be divided evenly between all remaining services.  This is less common, but might be used when you don't quite know how to distribute the services.  For instance, Administration might be split this way.

**Comment by jmcameron** [comment]
> Also, I am wondering if we can split this table into two table `allocation_basis` and `allocation_basis_value`
> 
> ```sql
> CREATE TABLE `allocation_basis` (
>   `id` mediumINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
>   `label` VARCHAR(100) NOT NULL,
>   `constant` TINYINT(1),
>   PRIMARY KEY (`id`)
> ) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;
> 
> CREATE TABLE `allocation_basis_value` (
>   `allocation_basis_id` MEDIUMINT(8) UNSIGNED NOT NULL,
>   `cost_center_id` MEDIUMINT(8) UNSIGNED NOT NULL,
>   `value` decimal(19,4) UNSIGNED DEFAULT NULL,
>   `function` VARCHAR(50)
> ) ENGINE=InnoDB DEFAULT CHARACTER SET = utf8mb4 DEFAULT COLLATE = utf8mb4_unicode_ci;
> ```

I like this.  I'll have to think about it a bit more before we "cut metal" (actually start coding it).

**Comment by jmcameron** [comment]
Closed in PRs https://github.com/IMA-WorldHealth/bhima/pull/5908, https://github.com/IMA-WorldHealth/bhima/pull/5909, https://github.com/IMA-WorldHealth/bhima/pull/5912, https://github.com/IMA-WorldHealth/bhima/pull/5916, and https://github.com/IMA-WorldHealth/bhima/pull/5924.
