### ISSUE TITLE
Updates for the Analysis Of Auxiliary Cashboxes report

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#6169]
Finance > Report > Analysis Of Auxiliary Cashboxes

**Suggestions**
- Fix name.  Since only one cashbox is shown at a time in the report, the report title should be singular:  
  Analysis of Auxiliary Cashbox  (leaving the menu item in plural is okay).
- Is it possible to move the legend above the title?  Note that items like this are usually labeled as "Legend".
![image](https://user-images.githubusercontent.com/62145/145612257-4e068563-9dff-4b7b-a6ac-b9045d398600.png)
- What goes into the "Target" column?  Is it necessary?
- Is it always the case that each cash box only handles one currency?  Is there any need for multiple currency support (eg, show the FC cashbox in $ which would need a currency selection in the client side).

**Comment by jniles** [comment]
@mbayopanda can you take a look at this one?

**Comment by lomamech** [comment]
The OHADA accounting system, advocates the use of transfer accounts, take the example of IMCK Tshikaji which has HBB and PAX, at the time of collection if the money comes out of the PAX cashier, this money will have to be placed in an account transfer and not in the main cashier, and when the money arrives at HBB it will be necessary to empty the transfer accounts, which is why the table is subdivided into three parts,

**Comment by lomamech** [comment]
@jmcameron  With the BHIMA system during payment at the cash register, the system automatically chooses the cash register to use in relation to each currency, and this report being a tool for monitoring the activities of the auxiliary cashbox registers, it is necessary to track the movement in each cashbox against currency

**Comment by jmcameron** [comment]
@lomamech Thanks for the explanations!
