### ISSUE TITLE
Logic bug in Shipment allows reuse of assets in other shipments

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#6523]
![image](https://user-images.githubusercontent.com/896472/162725921-01113b3b-62a6-4d49-ae5c-9ad3cd364979.png)

**Comment by jmcameron** [comment]
This is an inherent problem due to the separation of the creation of a shipment and the exit of the stock specified in the shipment.  This cannot be resolved until creation of a shipment automatically does the stock exit.

Note that recent PRs have improved the error messages when doing a stock exit for a shipment where some of the stock is not available.

**Comment by jniles** [comment]
I believe we can probably just mask the output by checking for all shipments not sent from that depot.  They shouldn't be _too_ many.  If we can pre-filter the lots/assets based on those shipments, it should work similarly to the expired stock.
