### ISSUE TITLE
Problem with drug packaging

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#6811]
The BHIMA system manages inventories (Medicines and other Pharmaceutical products) using the smallest unit

But the managers of stocks and depots take packaging and boxes into account.

This situation means that when managers use the BHIMA systems for stock entry and exit, they are forced to multiply for stock entries and divide for stock exits. without forgetting that the suppliers transmit the price of the articles by boxes and by units.

To overcome this difficulty, this issue proposes to add in the stock management parameters, the possibility of being able to provide information on the packaging of pharmaceutical products and to make certain calculations automatically,

when entering stock, for example, it would suffice to enter the number of boxes, for example 120, the packaging Box of 50, cost of the box 4.5 so that the BHIMA system automatically fills in the quantity at 6000 and the unit cost at 0.09

The same goes for the stock issue, the manager will only have to enter the number of boxes for the system to convert it into a smaller unit.

There will be no question of modifying the structure of the database, so as not to generate any error in the BHIMA database

**Comment by lomamech** [comment]
What do you think of this problem @jniles @mbayopanda @jmcameron

**Comment by jmcameron** [comment]
I've thought about this problem too.   Unfortunately, converting boxes to individual dose counts and corresponding price fixes has another problem:   When shipping from depot to depot, you want to retain it as packages.  You only need the individual dose counts when it gets to a dispensing depot.

**Comment by jmcameron** [comment]
Also see 
 - https://github.com/IMA-WorldHealth/bhima/issues/6651
 - https://github.com/IMA-WorldHealth/bhima/pull/6779#pullrequestreview-1073905533

**Comment by jmcameron** [comment]
Here is a possible approach to this problem
- Add another inventory field: "count per container". 
- On initial stock entry, record the count of items in each container/package and the set the unit cost to be for for the container/package.
- When the stock reaches a dispensing pharmacy, provide an option to "unpackage" to divide the package into multiple lots (individual does) with "count per container" == 1 and adjust the individual dose account appropriately.

This approach matches what happens in reality, but based on the comments in the items linked above (#6551 and #6779), it may involve some significant changes to BHIMA.

**Comment by lomamech** [comment]
> I've thought about this problem too. Unfortunately, converting boxes to individual dose counts and corresponding price fixes has another problem: When shipping from depot to depot, you want to retain it as packages. You only need the individual dose counts when it gets to a dispensing depot.

For example, if the Health Zone seeks to send 17 boxes of 20 tablets to a health facility, instead of entering 340 as the quantity, it can enter the number of boxes 17 packaging 20 and the value 340 be calculated and displayed in the interface automatically

**Comment by lomamech** [comment]
@jmcameron , I will consider this option **"Add another inventory field: "count per container".** " and @mbayopanda  suggested I find a way to save the conditioning in the Database

**Comment by jmcameron** [comment]
I suggest that unit_cost ALWAYS be for the unit cost of a individual unit. This follows the suggest from Chris based on earlier discussion:

> we held a meeting and decided to only interfere with the drugs in relation to the smallest unit, we took the resolution to be able to modify the label of the products without taking into account their packaging

 For pills, etc, it would be a single pill.  Note that this might not be enough for a single dose since sometimes a does is multiple pills.   For liquids, it is not quite as clear.  Should the smallest "unit" be a ml?  We would need to decide on a convention for liquids.   

The stock entry forms will need to be updated to handle this clearly.   In the database queries, we often compute costs based on quantity*unit_cost in the SQL query.  These would need to be changed to quantity*count_per_container*unit_cost.   We may need to add another column to some pages (like articles in stock, stock lots) that has the count_per_container.

We should think about what to call this.  Here are some suggestions

- package_count
- count_per_package
- num_per_package

- container_count ("container" may be better than "package" since it work better with both pills and liquids)
- count_per_container
- num_per_container

- count  (although this could be confused with 'quantity')
