### ISSUE TITLE
(refactor) Move depots/pharmacies and purchasing into Inventory

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#725]
I propose we move our Pharmacies module (used to be depots) and Purchase Order into the `/inventory/` namespace.  This means that both Purchase Order and Pharmacies will appear under the `Inventory` Tree Node and will have URLs `/inventory/purchases/` and `/inventory/pharmacies/`, respectively.

**Comment by jniles** [comment]
@mbayopanda, what do you think of this proposal?  Do you think it is worth working on, or do you think we should close it?

**Comment by mbayopanda** [comment]
@jniles for Purchase order there is also a registry `Registre des achats`. 

![image](https://user-images.githubusercontent.com/5445251/38089786-853a0980-3358-11e8-87b5-af7037013e8f.png)

About `depots/pharmacies` i think that we cannot put it inside inventory because it is a configuration module and it is about a different concept.

**Comment by jniles** [comment]
This likely will never be implemented.  It isn't a pressing need either.  Between shipments, assets, and other stock features, the design isn't as pure as this issue thought it might be.
