### ISSUE TITLE
Updates to Account Statement page

### ISSUE THREAD

**Issue by jmcameron** [Third-Culture-Software/bhima#7354]
Requested updates to report
- `Finance>Rapports/Rélevé de compte`
- `Finance>Reports/Account Statement`

The following items are based on feedback on https://github.com/IMA-WorldHealth/bhima/pull/7336
- [ ] Since the report is for ONE account, add the account number and title on the top-right of the PDF report
- [ ] Fix duplicated filters on the PDF report (forgot to check this before merging the PR)
- [ ] If the account_id is not cached in AppCache, the report page should automatically open the filter search modal.
- [ ] Should the grand totals go into the credit/debit columns on the PDF report?  Where does the difference go?  Or add an extra line at the bottom with those numbers (like the report page)?  Or put those numbers in the top right of the PDF output under the account number and name?

Finally, why does this report generate different output that the "Account Statement Report (Single)"?

**Comment by jniles** [comment]
For clarity, I believe the reason this generates a different result from the Account Statement is that it (1) doesn't take into account prior transactions (maybe this should be corrected) and (2) it only uses posted transactions to the general ledger.

If you are seeing something different than this, please describe the issue!

**Comment by jniles** [comment]
I'm adding some more things I've uncovered looking into this more:

- [ ] The comment modal is fairly bland.  It also uses a different style of commenting than the posting journal.  The journal uses "comment" in the dropdown menu, whereas the account statement uses "comment" in the toolbar.
- [ ] The currencies are broken in the report, showing in the incorrect currencies (USD, rather than the enterprise currency.

All of these are fixable, and I have started working on the, however ...

I'm leaning towards ripping this report out, based on @jmcameron logic that the functionality is found elsewhere.  The only user I know of that routinely uses it is Vanga, and I've reached out to them to get their opinion.

@mbayopanda do you have any thoughts on this?  Should we just remove it to reduce the workload of maintaining a lot of duplicated functionality?
