### ISSUE TITLE
Do not accept negative values for payroll indices

### ISSUE THREAD

**Issue by jniles** [Third-Culture-Software/bhima#7452]
Vanga really tied themselves in knots by putting in negative values to indice fields.  We should add a client-side rule to block the ability to put negative values in the indice fields.

![image](https://github.com/IMA-WorldHealth/bhima/assets/896472/71a31799-f5fd-48a1-b90e-438a937293f5)

**Comment by jmcameron** [comment]
I took a quick look at this.  It appears that `client/src/modules/multiple_payroll_indice/modals/config.modal.html uses bh-input-text` for these indexes.   There does not seem to be an easy way to prevent negative entries in a text field.  So I suggest creating a new controller: `bh-input-index` or 'bh-input-number' and set it up so that it can prevent negative numbers (based on an argument to the controller).   Note that the monetary values on the right are configured not to allow negative numbers.
Also, it was not clear to me why `bh-input-text` has any code in the controller for dealing with currency data.

**Comment by jniles** [comment]
I would suggest move away from `bhInputText` entirely in this case and just use an `<input type="number" min="0" ng-model="">` unless there is a really good reason to keep `bhInputText`.  Given the name, it sounds like it is built for text input, not numeric.  Most of what we would build into the `bhInputIndex` seems like it is already native to HTML's `<input>` box anyway.

**Comment by lomamech** [comment]
> I would suggest move away from `bhInputText` entirely in this case and just use an `<input type="number" min="0" ng-model="">` unless there is a really good reason to keep `bhInputText`. Given the name, it sounds like it is built for text input, not numeric. Most of what we would build into the `bhInputIndex` seems like it is already native to HTML's `<input>` box anyway.

I used bhInputText by setting the type parameter to number and adding the min property and it works fine
