### ISSUE TITLE
Journal entry error when customer invoice has a value of zero

### ISSUE THREAD

**Issue by mbayopanda** [Third-Culture-Software/bhima#7463]
With the SEMI project, some hospitals do not have to charge customers for medicines, so the value of the invoice will be zero, and for these cases, we do not have the correct writings in the journal.

<img width="1064" alt="image" src="https://github.com/IMA-WorldHealth/bhima/assets/5445251/37a80edd-d1fc-4631-8483-1d03be681a24">

**Comment by jniles** [comment]
Why have an invoice at all if the value is 0?

I think this can be solved in two ways. Either:

1) We instruct them not to make invoices.  The only reason to have an invoice in BHIMA is to account for patients with debt.

Or 

2) We charge the patient for the value of the drugs and services (for example, 5000FC), but immediately discount it with a subsidy.  That way, the amount due to the patient is 0, but the journal will have a double entry account of the income account for the services being billed on one side of the transaction and an expense account (or a subsidy account, whatever makes the most sense) on the other side.

**Comment by mbayopanda** [comment]
In BHIMA to give medicines to patients the patient must have an invoice, and to discourage patients from going to take the products at the pharmacy without any trace in BHIMA, we recommended going to the billing department.

**Comment by jniles** [comment]
We could add a setting in the enterprise settings to disable the requirement to link an invoice when distributing to a patient.  Would that solve the issue?

I'm a little weary of a BHIMA restriction causing us to have 0 value transactions, which seems strange.  After doing some googling, it looks like [Quickbooks also proposes the discount solution](https://quickbooks.intuit.com/learn-support/en-us/payments/create-invoice-with-zero-balance-due/00/1096890) instead of making a $0 invoice.

**Comment by jniles** [comment]
Seeing as there isn't much further discussion of this, I guess let us try it and find out what the negative repercussions are, if any?  My fears may not be well founded.

**Comment by jmcameron** [comment]
> Seeing as there isn't much further discussion of this, I guess let us try it and find out what the negative repercussions are, if any? My fears may not be well founded.

There is a PR for this now https://github.com/IMA-WorldHealth/bhima/pull/7468.  I had a concern about the input fields for patient invoices, that should be addressed before merging the PR.
