### ISSUE TITLE
Problem regarding the increase in basic indices based on percentages

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#7498]
After carrying out the first investigation we did not detect the error, but after trying to create new pay periods in advance for future years we did not notice the increase in the basic indices, this outcome is proposed to analyze this bug which occurs randomly

**Comment by lomamech** [comment]
@jniles I came back to this issue, just because I managed to reproduce the error although it seems to be random

**Comment by lomamech** [comment]
after carrying out investigations on the *UpdateStaffingIndices* procedure, the reasons for increasing the years of seniority seem to be very random, and I also noticed that if for one reason or another an employee did not work during the month in which he should have benefited from the increase, this employee will not be able to benefit from the increase in his basic index for the entire fiscal year, I propose to replace the *UpdateStaffingIndices* procedure for this.

**Comment by jniles** [comment]
@lomamech, I would encourage you to develop a test case that can be repeated.  If that is possible, then we'll know it isn't random (which is _much_ easier to fix).  Then we can write a small test and make sure our fix passes that test.  Since @jmcameron got BHIMA building on jenkins regularly, we'll likely be able to run this test over and over to ensure it never breaks again.  

Having employees not receive the amount of money they were due is a pretty risky bug for both BHIMA and the institution.  😨
