### ISSUE TITLE
Importing Payroll Configurations from an Excel File

### ISSUE THREAD

**Issue by lomamech** [Third-Culture-Software/bhima#7655]
This task aims to allow the human resources department or personnel management to configure payroll elements directly from an Excel file.

The template for this Excel file must first be imported from the BHIMA system and correspond to the selected pay period. This module has several advantages, including reducing the error rate and eliminating double checking.

**Comment by jniles** [comment]
I wonder if it might be worth trying to make payroll a little easier to use first, just because trying to maintain an interface for Excel will be a pain.  If that fails, then Excel it is.

Would it be possible to start by having a "Payroll Checklist" that has defaults from the previous pay period and users can simply click "Next >" through to choose all the elements of payroll?  One problem right now is that there is no way to tell what step person is on in the payroll process if they get interrupted.  It might be helpful to have some sort of UI to keep track of each step, validate it, and allow users to come back and see the decisions they made at each step (which pay period they used, which employees they configured, etc).

There have been a couple of previous issues designed to make payroll a little easier to use:

https://github.com/IMA-WorldHealth/bhima/issues/2577
https://github.com/IMA-WorldHealth/bhima/issues/6386

**Comment by lomamech** [comment]
> I wonder if it might be worth trying to make payroll a little easier to use first, just because trying to maintain an interface for Excel will be a pain. If that fails, then Excel it is.
> 
> Would it be possible to start by having a "Payroll Checklist" that has defaults from the previous pay period and users can simply click "Next >" through to choose all the elements of payroll? One problem right now is that there is no way to tell what step person is on in the payroll process if they get interrupted. It might be helpful to have some sort of UI to keep track of each step, validate it, and allow users to come back and see the decisions they made at each step (which pay period they used, which employees they configured, etc).
> 
> There have been a couple of previous issues designed to make payroll a little easier to use:
> 
> #2577 #6386

You are right to say so. In the first version of the payroll system from 2018, the classic method was simple because employees already had their base salary defined. Seniority bonuses, taxes, and various other deductions were calculated automatically. The only elements that needed to be configured each month were the bonuses (night shifts, public holidays, on-call shifts) since these elements are not static and did not apply to all employees.


However, the introduction of the payroll system with indices completely changed the logic, as bonuses and other benefits are no longer expressed in monetary values but in indices that need to be configured each month.

To avoid potential errors, we recommended that the payroll teams continue the configuration in Excel and cross-check the results in BHIMA to minimize the risk of errors.

The solution to improve the payroll system, in my opinion, would be to merge the classic system and the index-based system into a single payroll procedure. By rethinking the analysis and design of the new payroll module, we could also discuss with the stakeholders to implement a solution that would ease their tasks.
