### ISSUE TITLE
(feat) Cost center module implementation

### ISSUE THREAD

**Issue by mbayopanda** [third-culture-software/bhima#809]
This issue is about the implementation of the `Cost Center Module`, this module must be able to give BHIMA all required data for producing the `Cost Center Analysis Report`.

**Comment by sfount** [comment]
This issue is a great start. In order to begin implementing cost centres in 2.x we will need to start thinking about the core entities: 
- Cost centre database design/ schema 
- API design 
- Client side configuration module interface mock-up

I think it is important to run these designs by the whole team as there was as 1.x had some duplicated code/ database entities for cost and profit centres. If we can reduce the amount of duplicated code (individual code for both cost and profit centres) then we can continue to make 2.x a maintainable code base.

**Comment by DedrickEnc** [comment]
@sfount
Are you proposing indirectly  the use of one table, one client UI for cost and profit center? 
I think the API should be separated.

**Comment by sfount** [comment]
@DedrickEnc You are correct, I think that would be a good suggestion. 

Currently the schema is as follows 
**profit_center**
- project_id 
- id 
- text 
- note 

**cost_center**
- project_id
- id 
- text
- note 
- is_principal

A lot of similar information is captured in these two tables.

Because they are also seen as completely different entities within 1.x it means that there is a lot of code that is identical but just changes the table name. This duplication can be dangerous because updates to one set of code will not apply to both copies. 

For an example of this [profit_center.html](https://github.com/IMA-WorldHealth/bhima-1.X/blob/master/client/src/partials/profit_center/profit_center.html) and [cost_center.html](https://github.com/IMA-WorldHealth/bhima-1.X/blob/master/client/src/partials/cost_center/cost_center.html) from 1.x contain very similar structure/ code but would have to both be updated if something changed with the structure.

@DedrickEnc What do you think? Do you think you could propose a schema/ API design that doesn't require two different entities?

**Comment by DedrickEnc** [comment]
@sfount

In finance there is concept called **centre de frais** (may be fees center in english) which can combine them into one entity so, I will propose something.

**Comment by DedrickEnc** [comment]
Here is my proposal about the the cost center and profit center

## Schema

**fee_center**
- id --primary key
- project_id -- required
- label -- required
- is_cost  -- should be `1` if the record is a cost center and this column is required
- is_principal -- should be one for every profit center and cost center which are principal, this column is required
- note --not required

**cost_assignation**
- id -- primary key
- auxiliary_cost_id -- required
- value -- required, the total value of the auxiliary cost to split among principal cost center
- period_id --the period concerned by the assignation
- date -- required time-stamp
- allocation_key -- required, the criteria applied to allocate cost
- note -- not required

**cost_assignation_item**
- id --primary key
- cost_assignation_id -- required, the cost_assignation reference
- principal_cost_id --required, the principal cost selected to supported the part of the cost
- allocated_value --required, the value supported by the principal cost center selected

So the `cost_center_id` and `profit_center_id` from the `service` table should reference the table `fee_center`. 

## API

here are the initial list of interfaces found : 
- Method : `GET`,  PATH : `fee_centers/`, Returns all fee centers
- Method : `GET`,  PATH : `fee_centers/:is_cost`, Returns all cost/profit centers
- Method : `GET`,  PATH : `fee_centers/cost/:is_principal`, Returns all auxiliary/principal cost centers
- Method : `GET`,  PATH : `fee_centers/:id`, Returns a particular fee center
- Method : `POST`,  PATH : `fee_centers/`, Creates a fee center
- Method : `PUT`,  PATH : `fee_centers/:id`, Updates a fee center
- Method : `POST`,  PATH : `fee_centers/assignations`,  Assigns by creating records in cost_assignation and cost_assignation_item as a transaction
- Method : `GET`,  PATH : `fee_centers/assignations`, Returns all assignations

## User UI

The transaction type UI interface is a good inspiration for the CRUD, two separate state can be created to manage assignation and allocation.

@IMA-WorldHealth/bhima-core what do you think?

**Comment by sfount** [comment]
@DedrickEnc This proposal for combining into `fee_centers` looks excellent to me. 

One comment I have on the API is that 
`fee_centers/:is_cost` and `fee_centers/:id` will conflict - it will be impossible to know if the variable passed in is an ID or a cost. I would recommend that all filtering is done using a query string '?' for example `fee_centers?is_cost=true`. Leaving: 
`fee_centers/` - all fee centers 
`fee_centers/:id` - detailed information on a fee center 

I think it would be good to first build the database and API structure for fee centers and then design the assignment process/ API carefully once that is in place.

**Comment by DedrickEnc** [comment]
That works for me, if there is no inconvenient I will implement that.

**Comment by DedrickEnc** [comment]
Here is a mock-up for the listing and creation

@sfount 
for listing
![fee center list](https://cloud.githubusercontent.com/assets/5418919/19682869/79104b4c-9aa7-11e6-8d6a-86d9688c0b77.png)

And for creation
![edit_create fee center](https://cloud.githubusercontent.com/assets/5418919/19682848/68522b7c-9aa7-11e6-8885-b85eaf1e3fd3.png)

What do you think?

**Comment by jniles** [comment]
Can fee centers belonging to another project allocate costs to a fee center associated with a different project?

**Comment by DedrickEnc** [comment]
I am not understand, can you more clear?

**Comment by jniles** [comment]
Can costs be allocated across projects?  So, can PAX's electricity bill can be shared to HBB's maternity?

**Comment by DedrickEnc** [comment]
This is possible but not frequent. for example, the IMCK internet charge can be shared between PAX services and HBB services.
