### ISSUE TITLE
(design) Exchange Rate Dashboard UI

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#962]
This issue is to solicit ideas for a better design for the exchange rate display on the dashboard.  When the enterprise is run in a currency that is very small, you get the following large display:

![exchangeratedashboardinterface](https://cloud.githubusercontent.com/assets/896472/20657296/23f280dc-b535-11e6-81a3-347e7d6677ab.png)
_Fig 1: The Exchange Rate Display_

While this display is informative, it could be improved. One idea is the list `1 FC = X {{currency }}` on the bar, to help orient a user.

**Comment by sfount** [comment]
The very small number shown here is because this by default displays the exchange on 1 of the enterprise currency. In this case 1FC. 

In reality the smallest number of FC one could think about in dollars is 50 and you would normally only think of converting 1000. 

Potentially we could add a `display_value` to the currency table that will be used when the exchange rate has to be shown to the user. 

In this case it would then show `$0.87` (1000FC)

**Comment by jeremielodi** [comment]
Hi @jniles , can this issue be closed,
I worked on this PR #2063
