### ISSUE TITLE
Inventory groups configuration makes a request for every inventory groups 

### ISSUE THREAD

**Issue by sfount** [third-culture-software/bhima#991]
Inventory groups configuration currently lets you see how many inventory items are subscribed to a group. This (relatively) expensive calculation is requested and performed for every inventory group individually.  This results in **n** `GET` requests where **n** is the number of inventory groups. 

This information should be compiled and sent in one request - ideally it can be determined using a `GROUP_BY` to reduce MySQL connection requests.

**Comment by jniles** [comment]
This should be refactored to be a single GET request that totals the number of items in each inventory group.  Like this: `GET /inventory/groups?include_members=1`.  The inventory configuration page could then send a single GET request instead of many.

@lomamech, when you are doing with the translation key work, can do tackle this?
